server {
    listen 9000;
    server_name walhall-frontend;
    root /app/build/;
    index index.html;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_types
        application/atom+xml
        application/geo+json
        application/javascript
        application/x-javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rdf+xml
        application/rss+xml
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/svg+xml
        text/css
        text/html
        text/javascript
        text/plain
        text/xml;

    # Force all paths to load either itself (js files) or go through index.html.
    # disable cache on index.html
    location / {
        try_files $uri /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
    # cache static files
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
        access_log off;
    }
    location /images/ {
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }
    location /favicon.svg {
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }
}
