/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  InternalOrganization,
  InternalOrganizationPage,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/controlplane';

export const getListInternalOrganizationsResponseMock = (
  overrideResponse: Partial<InternalOrganizationPage> = {},
): InternalOrganizationPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    ...{
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      uuid: faker.string.uuid(),
      created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
      created_by: faker.string.uuid(),
      updated_at: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        'active',
        'deleting',
        'delete_failed',
        'deleted',
      ] as const),
      plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
  })),
  next_page_token: undefined,
  ...overrideResponse,
});

export const getListInternalOrganizationsResponseMock200 = (
  overrideResponse: Partial<InternalOrganizationPage> = {},
): InternalOrganizationPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    ...{
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      uuid: faker.string.uuid(),
      created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
      created_by: faker.string.uuid(),
      updated_at: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split('.')[0]}Z`,
        undefined,
      ]),
      status: faker.helpers.arrayElement([
        'active',
        'deleting',
        'delete_failed',
        'deleted',
      ] as const),
      plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
  })),
  next_page_token: undefined,
  ...overrideResponse,
});

export const getCreateInternalOrganizationResponseMock = (): InternalOrganization => ({
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    uuid: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    created_by: faker.string.uuid(),
    updated_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
    status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
    plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
});

export const getCreateInternalOrganizationResponseMock201 = (): InternalOrganization => ({
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    uuid: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    created_by: faker.string.uuid(),
    updated_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
    status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
    plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
});

export const getCreateInternalOrganizationResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateInternalOrganizationResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetInternalOrganizationResponseMock = (): InternalOrganization => ({
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    uuid: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    created_by: faker.string.uuid(),
    updated_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
    status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
    plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
});

export const getGetInternalOrganizationResponseMock200 = (): InternalOrganization => ({
  ...{
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    uuid: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    created_by: faker.string.uuid(),
    updated_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
    status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
    plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{ source: faker.helpers.arrayElement(['internal', 'public'] as const) },
});

export const getGetInternalOrganizationResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getListInternalOrganizationsMockHandler = (
  overrideResponse?:
    | InternalOrganizationPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InternalOrganizationPage> | InternalOrganizationPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListInternalOrganizationsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getListInternalOrganizationsMockHandler200 = (
  overrideResponse?:
    | InternalOrganizationPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InternalOrganizationPage> | InternalOrganizationPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListInternalOrganizationsResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateInternalOrganizationMockHandler = (
  overrideResponse?:
    | InternalOrganization
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<InternalOrganization> | InternalOrganization),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateInternalOrganizationResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateInternalOrganizationMockHandler201 = (
  overrideResponse?:
    | InternalOrganization
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<InternalOrganization> | InternalOrganization),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateInternalOrganizationResponseMock201(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateInternalOrganizationMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateInternalOrganizationResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateInternalOrganizationMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/internal/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateInternalOrganizationResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetInternalOrganizationMockHandler = (
  overrideResponse?:
    | InternalOrganization
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InternalOrganization> | InternalOrganization),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/internal/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetInternalOrganizationResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetInternalOrganizationMockHandler200 = (
  overrideResponse?:
    | InternalOrganization
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InternalOrganization> | InternalOrganization),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/internal/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetInternalOrganizationResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetInternalOrganizationMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/internal/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetInternalOrganizationResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getOrganizationsMock = () => [
  getListInternalOrganizationsMockHandler(),
  getCreateInternalOrganizationMockHandler(),
  getGetInternalOrganizationMockHandler(),
];
