/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  InternalOrganization,
  InternalOrganizationCreateBody,
  InternalOrganizationPage,
  ListInternalOrganizationsParams,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/controlplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List internal state for Organizations
 */
export const listInternalOrganizations = (
  params?: ListInternalOrganizationsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InternalOrganizationPage>(
    { url: `/internal/orgs`, method: 'GET', params, signal },
    options,
  );
};

export const getListInternalOrganizationsQueryKey = (params?: ListInternalOrganizationsParams) => {
  return [`/internal/orgs`, ...(params ? [params] : [])] as const;
};

export const getListInternalOrganizationsQueryOptions = <
  TData = Awaited<ReturnType<typeof listInternalOrganizations>>,
  TError = ErrorType<unknown>,
>(
  params?: ListInternalOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listInternalOrganizations>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListInternalOrganizationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listInternalOrganizations>>> = ({
    signal,
  }) => listInternalOrganizations(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listInternalOrganizations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListInternalOrganizationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listInternalOrganizations>>
>;
export type ListInternalOrganizationsQueryError = ErrorType<unknown>;

export function useListInternalOrganizations<
  TData = Awaited<ReturnType<typeof listInternalOrganizations>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | ListInternalOrganizationsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listInternalOrganizations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInternalOrganizations>>,
          TError,
          Awaited<ReturnType<typeof listInternalOrganizations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListInternalOrganizations<
  TData = Awaited<ReturnType<typeof listInternalOrganizations>>,
  TError = ErrorType<unknown>,
>(
  params?: ListInternalOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listInternalOrganizations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInternalOrganizations>>,
          TError,
          Awaited<ReturnType<typeof listInternalOrganizations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListInternalOrganizations<
  TData = Awaited<ReturnType<typeof listInternalOrganizations>>,
  TError = ErrorType<unknown>,
>(
  params?: ListInternalOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listInternalOrganizations>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List internal state for Organizations
 */

/**
 *
 */
export function useListInternalOrganizations<
  TData = Awaited<ReturnType<typeof listInternalOrganizations>>,
  TError = ErrorType<unknown>,
>(
  params?: ListInternalOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listInternalOrganizations>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListInternalOrganizationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create the internal state for an Organization
 */
export const createInternalOrganization = (
  internalOrganizationCreateBody: InternalOrganizationCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InternalOrganization>(
    {
      url: `/internal/orgs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: internalOrganizationCreateBody,
      signal,
    },
    options,
  );
};

export const getCreateInternalOrganizationMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInternalOrganization>>,
    TError,
    { data: InternalOrganizationCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInternalOrganization>>,
  TError,
  { data: InternalOrganizationCreateBody },
  TContext
> => {
  const mutationKey = ['createInternalOrganization'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInternalOrganization>>,
    { data: InternalOrganizationCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return createInternalOrganization(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInternalOrganizationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInternalOrganization>>
>;
export type CreateInternalOrganizationMutationBody = InternalOrganizationCreateBody;
export type CreateInternalOrganizationMutationError = ErrorType<
  N400BadRequestResponse | N409ConflictResponse
>;

/**
 * @summary Create the internal state for an Organization
 */
export const useCreateInternalOrganization = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInternalOrganization>>,
      TError,
      { data: InternalOrganizationCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInternalOrganization>>,
  TError,
  { data: InternalOrganizationCreateBody },
  TContext
> => {
  const mutationOptions = getCreateInternalOrganizationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get internal state for Organization
 */
export const getInternalOrganization = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InternalOrganization>(
    { url: `/internal/orgs/${orgId}`, method: 'GET', signal },
    options,
  );
};

export const getGetInternalOrganizationQueryKey = (orgId?: string) => {
  return [`/internal/orgs/${orgId}`] as const;
};

export const getGetInternalOrganizationQueryOptions = <
  TData = Awaited<ReturnType<typeof getInternalOrganization>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInternalOrganization>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInternalOrganizationQueryKey(orgId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInternalOrganization>>> = ({
    signal,
  }) => getInternalOrganization(orgId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInternalOrganization>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInternalOrganizationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInternalOrganization>>
>;
export type GetInternalOrganizationQueryError = ErrorType<N404NotFoundResponse>;

export function useGetInternalOrganization<
  TData = Awaited<ReturnType<typeof getInternalOrganization>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInternalOrganization>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInternalOrganization>>,
          TError,
          Awaited<ReturnType<typeof getInternalOrganization>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInternalOrganization<
  TData = Awaited<ReturnType<typeof getInternalOrganization>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInternalOrganization>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInternalOrganization>>,
          TError,
          Awaited<ReturnType<typeof getInternalOrganization>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInternalOrganization<
  TData = Awaited<ReturnType<typeof getInternalOrganization>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInternalOrganization>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get internal state for Organization
 */

/**
 *
 */
export function useGetInternalOrganization<
  TData = Awaited<ReturnType<typeof getInternalOrganization>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInternalOrganization>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetInternalOrganizationQueryOptions(orgId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
