/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  ListModulesParams,
  ListModuleVersionsParams,
  Module,
  ModuleCreateBody,
  ModulePage,
  ModuleUpdateBody,
  ModuleVersion,
  ModuleVersionPage,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/controlplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List modules in the org
 */
export const listModules = (
  orgId: string,
  params?: ListModulesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ModulePage>(
    { url: `/orgs/${orgId}/modules`, method: 'GET', params, signal },
    options,
  );
};

export const getListModulesQueryKey = (orgId?: string, params?: ListModulesParams) => {
  return [`/orgs/${orgId}/modules`, ...(params ? [params] : [])] as const;
};

export const getListModulesQueryOptions = <
  TData = Awaited<ReturnType<typeof listModules>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListModulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModules>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListModulesQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listModules>>> = ({ signal }) =>
    listModules(orgId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listModules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListModulesQueryResult = NonNullable<Awaited<ReturnType<typeof listModules>>>;
export type ListModulesQueryError = ErrorType<N404NotFoundResponse>;

export function useListModules<
  TData = Awaited<ReturnType<typeof listModules>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params: undefined | ListModulesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModules>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModules>>,
          TError,
          Awaited<ReturnType<typeof listModules>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListModules<
  TData = Awaited<ReturnType<typeof listModules>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListModulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModules>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModules>>,
          TError,
          Awaited<ReturnType<typeof listModules>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListModules<
  TData = Awaited<ReturnType<typeof listModules>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListModulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModules>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List modules in the org
 */

/**
 *
 */
export function useListModules<
  TData = Awaited<ReturnType<typeof listModules>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListModulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModules>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListModulesQueryOptions(orgId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new modules in the org
 */
export const createModule = (
  orgId: string,
  moduleCreateBody: ModuleCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Module>(
    {
      url: `/orgs/${orgId}/modules`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: moduleCreateBody,
      signal,
    },
    options,
  );
};

export const getCreateModuleMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createModule>>,
    TError,
    { orgId: string; data: ModuleCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createModule>>,
  TError,
  { orgId: string; data: ModuleCreateBody },
  TContext
> => {
  const mutationKey = ['createModule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createModule>>,
    { orgId: string; data: ModuleCreateBody }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return createModule(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateModuleMutationResult = NonNullable<Awaited<ReturnType<typeof createModule>>>;
export type CreateModuleMutationBody = ModuleCreateBody;
export type CreateModuleMutationError = ErrorType<N400BadRequestResponse | N409ConflictResponse>;

/**
 * @summary Create a new modules in the org
 */
export const useCreateModule = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createModule>>,
      TError,
      { orgId: string; data: ModuleCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createModule>>,
  TError,
  { orgId: string; data: ModuleCreateBody },
  TContext
> => {
  const mutationOptions = getCreateModuleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get an existing module in the org
 */
export const getModule = (
  orgId: string,
  moduleId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Module>(
    { url: `/orgs/${orgId}/modules/${moduleId}`, method: 'GET', signal },
    options,
  );
};

export const getGetModuleQueryKey = (orgId?: string, moduleId?: string) => {
  return [`/orgs/${orgId}/modules/${moduleId}`] as const;
};

export const getGetModuleQueryOptions = <
  TData = Awaited<ReturnType<typeof getModule>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModule>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetModuleQueryKey(orgId, moduleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getModule>>> = ({ signal }) =>
    getModule(orgId, moduleId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!(orgId && moduleId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getModule>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetModuleQueryResult = NonNullable<Awaited<ReturnType<typeof getModule>>>;
export type GetModuleQueryError = ErrorType<N404NotFoundResponse>;

export function useGetModule<
  TData = Awaited<ReturnType<typeof getModule>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModule>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModule>>,
          TError,
          Awaited<ReturnType<typeof getModule>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetModule<
  TData = Awaited<ReturnType<typeof getModule>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModule>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModule>>,
          TError,
          Awaited<ReturnType<typeof getModule>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetModule<
  TData = Awaited<ReturnType<typeof getModule>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModule>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get an existing module in the org
 */

/**
 *
 */
export function useGetModule<
  TData = Awaited<ReturnType<typeof getModule>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModule>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetModuleQueryOptions(orgId, moduleId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an existing module
 */
export const updateModule = (
  orgId: string,
  moduleId: string,
  moduleUpdateBody: ModuleUpdateBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Module>(
    {
      url: `/orgs/${orgId}/modules/${moduleId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: moduleUpdateBody,
    },
    options,
  );
};

export const getUpdateModuleMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateModule>>,
    TError,
    { orgId: string; moduleId: string; data: ModuleUpdateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateModule>>,
  TError,
  { orgId: string; moduleId: string; data: ModuleUpdateBody },
  TContext
> => {
  const mutationKey = ['updateModule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateModule>>,
    { orgId: string; moduleId: string; data: ModuleUpdateBody }
  > = (props) => {
    const { orgId, moduleId, data } = props ?? {};

    return updateModule(orgId, moduleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateModuleMutationResult = NonNullable<Awaited<ReturnType<typeof updateModule>>>;
export type UpdateModuleMutationBody = ModuleUpdateBody;
export type UpdateModuleMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Update an existing module
 */
export const useUpdateModule = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateModule>>,
      TError,
      { orgId: string; moduleId: string; data: ModuleUpdateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateModule>>,
  TError,
  { orgId: string; moduleId: string; data: ModuleUpdateBody },
  TContext
> => {
  const mutationOptions = getUpdateModuleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete an existing module in the org if it is unused
 */
export const deleteModule = (
  orgId: string,
  moduleId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/orgs/${orgId}/modules/${moduleId}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteModuleMutationOptions = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteModule>>,
    TError,
    { orgId: string; moduleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteModule>>,
  TError,
  { orgId: string; moduleId: string },
  TContext
> => {
  const mutationKey = ['deleteModule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteModule>>,
    { orgId: string; moduleId: string }
  > = (props) => {
    const { orgId, moduleId } = props ?? {};

    return deleteModule(orgId, moduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteModuleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModule>>>;

export type DeleteModuleMutationError = ErrorType<N404NotFoundResponse | N409ConflictResponse>;

/**
 * @summary Delete an existing module in the org if it is unused
 */
export const useDeleteModule = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteModule>>,
      TError,
      { orgId: string; moduleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteModule>>,
  TError,
  { orgId: string; moduleId: string },
  TContext
> => {
  const mutationOptions = getDeleteModuleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List the versions of a module
 */
export const listModuleVersions = (
  orgId: string,
  moduleId: string,
  params?: ListModuleVersionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ModuleVersionPage>(
    { url: `/orgs/${orgId}/modules/${moduleId}/versions`, method: 'GET', params, signal },
    options,
  );
};

export const getListModuleVersionsQueryKey = (
  orgId?: string,
  moduleId?: string,
  params?: ListModuleVersionsParams,
) => {
  return [`/orgs/${orgId}/modules/${moduleId}/versions`, ...(params ? [params] : [])] as const;
};

export const getListModuleVersionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listModuleVersions>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  params?: ListModuleVersionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModuleVersions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListModuleVersionsQueryKey(orgId, moduleId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listModuleVersions>>> = ({ signal }) =>
    listModuleVersions(orgId, moduleId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!(orgId && moduleId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listModuleVersions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListModuleVersionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listModuleVersions>>
>;
export type ListModuleVersionsQueryError = ErrorType<N404NotFoundResponse>;

export function useListModuleVersions<
  TData = Awaited<ReturnType<typeof listModuleVersions>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  params: undefined | ListModuleVersionsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModuleVersions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModuleVersions>>,
          TError,
          Awaited<ReturnType<typeof listModuleVersions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListModuleVersions<
  TData = Awaited<ReturnType<typeof listModuleVersions>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  params?: ListModuleVersionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listModuleVersions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listModuleVersions>>,
          TError,
          Awaited<ReturnType<typeof listModuleVersions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListModuleVersions<
  TData = Awaited<ReturnType<typeof listModuleVersions>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  params?: ListModuleVersionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModuleVersions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List the versions of a module
 */

/**
 *
 */
export function useListModuleVersions<
  TData = Awaited<ReturnType<typeof listModuleVersions>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  params?: ListModuleVersionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listModuleVersions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListModuleVersionsQueryOptions(orgId, moduleId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a previous module version in the org
 */
export const getModuleVersion = (
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ModuleVersion>(
    {
      url: `/orgs/${orgId}/modules/${moduleId}/versions/${moduleVersionId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetModuleVersionQueryKey = (
  orgId?: string,
  moduleId?: string,
  moduleVersionId?: string,
) => {
  return [`/orgs/${orgId}/modules/${moduleId}/versions/${moduleVersionId}`] as const;
};

export const getGetModuleVersionQueryOptions = <
  TData = Awaited<ReturnType<typeof getModuleVersion>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetModuleVersionQueryKey(orgId, moduleId, moduleVersionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleVersion>>> = ({ signal }) =>
    getModuleVersion(orgId, moduleId, moduleVersionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && moduleId && moduleVersionId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetModuleVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleVersion>>>;
export type GetModuleVersionQueryError = ErrorType<N404NotFoundResponse>;

export function useGetModuleVersion<
  TData = Awaited<ReturnType<typeof getModuleVersion>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleVersion>>,
          TError,
          Awaited<ReturnType<typeof getModuleVersion>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetModuleVersion<
  TData = Awaited<ReturnType<typeof getModuleVersion>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleVersion>>,
          TError,
          Awaited<ReturnType<typeof getModuleVersion>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetModuleVersion<
  TData = Awaited<ReturnType<typeof getModuleVersion>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a previous module version in the org
 */

/**
 *
 */
export function useGetModuleVersion<
  TData = Awaited<ReturnType<typeof getModuleVersion>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  moduleId: string,
  moduleVersionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleVersion>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetModuleVersionQueryOptions(orgId, moduleId, moduleVersionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
