/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  ListActiveResourceNodesPage,
  ListActiveResourceNodesParams,
  N400BadRequestResponse,
  N404NotFoundResponse,
} from '../../../../../models/v2/dataplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List active resource nodes matching the query. At the moment, project_id and env_id are required.
 
 * @summary List active resource nodes
 */
export const listActiveResourceNodes = (
  orgId: string,
  params?: ListActiveResourceNodesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListActiveResourceNodesPage>(
    { url: `/orgs/${orgId}/active-resources`, method: 'GET', params, signal },
    options,
  );
};

export const getListActiveResourceNodesQueryKey = (
  orgId?: string,
  params?: ListActiveResourceNodesParams,
) => {
  return [`/orgs/${orgId}/active-resources`, ...(params ? [params] : [])] as const;
};

export const getListActiveResourceNodesQueryOptions = <
  TData = Awaited<ReturnType<typeof listActiveResourceNodes>>,
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListActiveResourceNodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listActiveResourceNodes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListActiveResourceNodesQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listActiveResourceNodes>>> = ({
    signal,
  }) => listActiveResourceNodes(orgId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listActiveResourceNodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListActiveResourceNodesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listActiveResourceNodes>>
>;
export type ListActiveResourceNodesQueryError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

export function useListActiveResourceNodes<
  TData = Awaited<ReturnType<typeof listActiveResourceNodes>>,
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
>(
  orgId: string,
  params: undefined | ListActiveResourceNodesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listActiveResourceNodes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveResourceNodes>>,
          TError,
          Awaited<ReturnType<typeof listActiveResourceNodes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListActiveResourceNodes<
  TData = Awaited<ReturnType<typeof listActiveResourceNodes>>,
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListActiveResourceNodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listActiveResourceNodes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveResourceNodes>>,
          TError,
          Awaited<ReturnType<typeof listActiveResourceNodes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListActiveResourceNodes<
  TData = Awaited<ReturnType<typeof listActiveResourceNodes>>,
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListActiveResourceNodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listActiveResourceNodes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List active resource nodes
 */

/**
 *
 */
export function useListActiveResourceNodes<
  TData = Awaited<ReturnType<typeof listActiveResourceNodes>>,
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListActiveResourceNodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listActiveResourceNodes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListActiveResourceNodesQueryOptions(orgId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
