/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  Jwks,
  N404NotFoundResponse,
  OpenidConfiguration,
} from '../../../../../models/v2/dataplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Show OIDC discovery configuration.
 */
export const getOpenidConfiguration = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OpenidConfiguration>(
    { url: `/.well-known/openid-configuration`, method: 'GET', signal },
    options,
  );
};

export const getGetOpenidConfigurationQueryKey = () => {
  return [`/.well-known/openid-configuration`] as const;
};

export const getGetOpenidConfigurationQueryOptions = <
  TData = Awaited<ReturnType<typeof getOpenidConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getOpenidConfiguration>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOpenidConfigurationQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpenidConfiguration>>> = ({ signal }) =>
    getOpenidConfiguration(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOpenidConfiguration>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOpenidConfigurationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOpenidConfiguration>>
>;
export type GetOpenidConfigurationQueryError = ErrorType<N404NotFoundResponse>;

export function useGetOpenidConfiguration<
  TData = Awaited<ReturnType<typeof getOpenidConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOpenidConfiguration>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenidConfiguration>>,
          TError,
          Awaited<ReturnType<typeof getOpenidConfiguration>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOpenidConfiguration<
  TData = Awaited<ReturnType<typeof getOpenidConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOpenidConfiguration>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenidConfiguration>>,
          TError,
          Awaited<ReturnType<typeof getOpenidConfiguration>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOpenidConfiguration<
  TData = Awaited<ReturnType<typeof getOpenidConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOpenidConfiguration>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Show OIDC discovery configuration.
 */

/**
 *
 */
export function useGetOpenidConfiguration<
  TData = Awaited<ReturnType<typeof getOpenidConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOpenidConfiguration>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOpenidConfigurationQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Show JSON Web Keys Set (JWKS).
 */
export const getJwks = (options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<Jwks>({ url: `/.well-known/jwks`, method: 'GET', signal }, options);
};

export const getGetJwksQueryKey = () => {
  return [`/.well-known/jwks`] as const;
};

export const getGetJwksQueryOptions = <
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = ErrorType<N404NotFoundResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJwksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJwks>>> = ({ signal }) =>
    getJwks(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getJwks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJwksQueryResult = NonNullable<Awaited<ReturnType<typeof getJwks>>>;
export type GetJwksQueryError = ErrorType<N404NotFoundResponse>;

export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJwks>>,
          TError,
          Awaited<ReturnType<typeof getJwks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJwks>>,
          TError,
          Awaited<ReturnType<typeof getJwks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Show JSON Web Keys Set (JWKS).
 */

/**
 *
 */
export function useGetJwks<
  TData = Awaited<ReturnType<typeof getJwks>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getJwks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetJwksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
