/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  ListMetadataKeysParams,
  MetadataKey,
  MetadataKeyCreateBody,
  MetadataKeyPage,
  MetadataKeyUpdateBody,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/dataplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of metadata keys for the specified organization. Each key is represented as a JSON object
containing the key name, type, and other attributes.
 
 * @summary List metadata keys for an organization
 */
export const listMetadataKeys = (
  orgId: string,
  params?: ListMetadataKeysParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MetadataKeyPage>(
    { url: `/orgs/${orgId}/metadata-keys`, method: 'GET', params, signal },
    options,
  );
};

export const getListMetadataKeysQueryKey = (orgId?: string, params?: ListMetadataKeysParams) => {
  return [`/orgs/${orgId}/metadata-keys`, ...(params ? [params] : [])] as const;
};

export const getListMetadataKeysQueryOptions = <
  TData = Awaited<ReturnType<typeof listMetadataKeys>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListMetadataKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMetadataKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMetadataKeysQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMetadataKeys>>> = ({ signal }) =>
    listMetadataKeys(orgId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMetadataKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMetadataKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listMetadataKeys>>>;
export type ListMetadataKeysQueryError = ErrorType<N404NotFoundResponse>;

export function useListMetadataKeys<
  TData = Awaited<ReturnType<typeof listMetadataKeys>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params: undefined | ListMetadataKeysParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMetadataKeys>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMetadataKeys>>,
          TError,
          Awaited<ReturnType<typeof listMetadataKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMetadataKeys<
  TData = Awaited<ReturnType<typeof listMetadataKeys>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListMetadataKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMetadataKeys>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMetadataKeys>>,
          TError,
          Awaited<ReturnType<typeof listMetadataKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMetadataKeys<
  TData = Awaited<ReturnType<typeof listMetadataKeys>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListMetadataKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMetadataKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List metadata keys for an organization
 */

/**
 *
 */
export function useListMetadataKeys<
  TData = Awaited<ReturnType<typeof listMetadataKeys>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListMetadataKeysParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMetadataKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMetadataKeysQueryOptions(orgId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a new metadata key for the specified organization. The request body should contain the key name,
type, and other attributes.
 
 * @summary Create a new metadata key for an organization
 */
export const createMetadataKey = (
  orgId: string,
  metadataKeyCreateBody: MetadataKeyCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MetadataKey>(
    {
      url: `/orgs/${orgId}/metadata-keys`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: metadataKeyCreateBody,
      signal,
    },
    options,
  );
};

export const getCreateMetadataKeyMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMetadataKey>>,
    TError,
    { orgId: string; data: MetadataKeyCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMetadataKey>>,
  TError,
  { orgId: string; data: MetadataKeyCreateBody },
  TContext
> => {
  const mutationKey = ['createMetadataKey'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMetadataKey>>,
    { orgId: string; data: MetadataKeyCreateBody }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return createMetadataKey(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMetadataKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMetadataKey>>
>;
export type CreateMetadataKeyMutationBody = MetadataKeyCreateBody;
export type CreateMetadataKeyMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Create a new metadata key for an organization
 */
export const useCreateMetadataKey = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createMetadataKey>>,
      TError,
      { orgId: string; data: MetadataKeyCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createMetadataKey>>,
  TError,
  { orgId: string; data: MetadataKeyCreateBody },
  TContext
> => {
  const mutationOptions = getCreateMetadataKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns the details of a specific metadata key for the specified organization. The response includes
the key name, type, and other attributes.
 
 * @summary Get a metadata key for an organization
 */
export const getMetadataKey = (
  orgId: string,
  metadataKeyName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MetadataKey>(
    { url: `/orgs/${orgId}/metadata-keys/${metadataKeyName}`, method: 'GET', signal },
    options,
  );
};

export const getGetMetadataKeyQueryKey = (orgId?: string, metadataKeyName?: string) => {
  return [`/orgs/${orgId}/metadata-keys/${metadataKeyName}`] as const;
};

export const getGetMetadataKeyQueryOptions = <
  TData = Awaited<ReturnType<typeof getMetadataKey>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  metadataKeyName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMetadataKeyQueryKey(orgId, metadataKeyName);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetadataKey>>> = ({ signal }) =>
    getMetadataKey(orgId, metadataKeyName, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && metadataKeyName),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetMetadataKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getMetadataKey>>>;
export type GetMetadataKeyQueryError = ErrorType<N404NotFoundResponse>;

export function useGetMetadataKey<
  TData = Awaited<ReturnType<typeof getMetadataKey>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  metadataKeyName: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataKey>>,
          TError,
          Awaited<ReturnType<typeof getMetadataKey>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMetadataKey<
  TData = Awaited<ReturnType<typeof getMetadataKey>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  metadataKeyName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataKey>>,
          TError,
          Awaited<ReturnType<typeof getMetadataKey>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMetadataKey<
  TData = Awaited<ReturnType<typeof getMetadataKey>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  metadataKeyName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a metadata key for an organization
 */

/**
 *
 */
export function useGetMetadataKey<
  TData = Awaited<ReturnType<typeof getMetadataKey>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  metadataKeyName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetadataKey>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMetadataKeyQueryOptions(orgId, metadataKeyName, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Deletes a specific metadata key for the specified organization. The request body should contain the key name.
 
 * @summary Delete a metadata key for an organization
 */
export const deleteMetadataKey = (
  orgId: string,
  metadataKeyName: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/orgs/${orgId}/metadata-keys/${metadataKeyName}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteMetadataKeyMutationOptions = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMetadataKey>>,
    TError,
    { orgId: string; metadataKeyName: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMetadataKey>>,
  TError,
  { orgId: string; metadataKeyName: string },
  TContext
> => {
  const mutationKey = ['deleteMetadataKey'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMetadataKey>>,
    { orgId: string; metadataKeyName: string }
  > = (props) => {
    const { orgId, metadataKeyName } = props ?? {};

    return deleteMetadataKey(orgId, metadataKeyName, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMetadataKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMetadataKey>>
>;

export type DeleteMetadataKeyMutationError = ErrorType<N404NotFoundResponse>;

/**
 * @summary Delete a metadata key for an organization
 */
export const useDeleteMetadataKey = <TError = ErrorType<N404NotFoundResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMetadataKey>>,
      TError,
      { orgId: string; metadataKeyName: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMetadataKey>>,
  TError,
  { orgId: string; metadataKeyName: string },
  TContext
> => {
  const mutationOptions = getDeleteMetadataKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Updates a specific metadata key for the specified organization. The request body should contain the updated
attributes of the metadata key.
 
 * @summary Update a metadata key for an organization
 */
export const updateMetadataKey = (
  orgId: string,
  metadataKeyName: string,
  metadataKeyUpdateBody: MetadataKeyUpdateBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<MetadataKey>(
    {
      url: `/orgs/${orgId}/metadata-keys/${metadataKeyName}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: metadataKeyUpdateBody,
    },
    options,
  );
};

export const getUpdateMetadataKeyMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMetadataKey>>,
    TError,
    { orgId: string; metadataKeyName: string; data: MetadataKeyUpdateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMetadataKey>>,
  TError,
  { orgId: string; metadataKeyName: string; data: MetadataKeyUpdateBody },
  TContext
> => {
  const mutationKey = ['updateMetadataKey'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMetadataKey>>,
    { orgId: string; metadataKeyName: string; data: MetadataKeyUpdateBody }
  > = (props) => {
    const { orgId, metadataKeyName, data } = props ?? {};

    return updateMetadataKey(orgId, metadataKeyName, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMetadataKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMetadataKey>>
>;
export type UpdateMetadataKeyMutationBody = MetadataKeyUpdateBody;
export type UpdateMetadataKeyMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Update a metadata key for an organization
 */
export const useUpdateMetadataKey = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMetadataKey>>,
      TError,
      { orgId: string; metadataKeyName: string; data: MetadataKeyUpdateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateMetadataKey>>,
  TError,
  { orgId: string; metadataKeyName: string; data: MetadataKeyUpdateBody },
  TContext
> => {
  const mutationOptions = getUpdateMetadataKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
