/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export interface BaseDeviceLoginRequest {
  /** The id of the device login request */
  id: string;
  /** The time at which the device login request was created. */
  created_at: string;
  /** The time at which this device login request will expire. */
  expires_at: string;
}
