/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { CurrentUserAllOf } from './currentUserAllOf';
import type { User } from './user';

export type CurrentUser = User & CurrentUserAllOf;
