/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */

export interface InternalAuthorizeBodyCheck {
  /**
   * The resource to check permissions on.
   *
   * @pattern ^(organization:.*)$
   */
  resource: string;
  /** The permission string. */
  permission: string;
}
