/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A payload needed to login a user against an identity provider.
 */
export interface LoginUserBody {
  /** The login provider type. */
  provider: string;
  /** An id token that allows us to look up the real user identifiers. */
  provider_token: string;
}
