/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { Error } from './error';

/**
 * Server understands the request but refuses to authorize it.
 */
export type N403ForbiddenResponse = Error;
