/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { OrgMembership } from './orgMembership';

/**
 * A page of org memberships
 */
export interface OrgMembershipPage {
  items: OrgMembership[];
  /** The page token to use to request the next page of items */
  next_page_token?: string;
}
