/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { PermissionDefinitionLevel } from './permissionDefinitionLevel';
import type { PermissionDefinitionScopesItem } from './permissionDefinitionScopesItem';

/**
 * A granular Platform Orchestrator permission.
 */
export interface PermissionDefinition {
  /** The exact identifier to include in a role permissions array. */
  id: string;
  display_name: string;
  description: string;
  /** A stable human-readable group for permission selection interfaces. */
  category: string;
  /** The legacy access class used to preserve the behavior of built-in roles. */
  level: PermissionDefinitionLevel;
  /**
   * The role assignment scopes where this permission is effective.
   *
   * @minItems 1
   */
  scopes: PermissionDefinitionScopesItem[];
}
