/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type RegisteredUserAllOf = {
  /** Whether an existing user already matched this login identity and could be returned */
  identity_already_exists: boolean;
};
