/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { RegisteredUserAllOf } from './registeredUserAllOf';
import type { User } from './user';

export type RegisteredUser = User & RegisteredUserAllOf;
