/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export interface ResourcePermissionCheck {
  /**
   * The resource to check permissions on.
   *
   * @pattern ^(organization|project|env):[a-zA-Z0-9/_|\-=+]+$
   */
  resource: string;
  /**
   * The permission string.
   *
   * @pattern ^[a-z][a-z0-9_]{1,62}[a-z0-9]$
   */
  permission: string;
}
