/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The configurable fields of an organization role.
 */
export interface RoleWriteBody {
  /**
   * @minLength 2
   * @maxLength 100
   * @pattern ^[^\p{Cc}\p{Cs}\p{Z}\n]( |[^\p{Cc}\p{Cs}\p{Z}\n])*[^\p{Cc}\p{Cs}\p{Z}\n]$
   */
  display_name: string;
  /** @minItems 1 */
  permissions: string[];
}
