/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A role within an organization that can be assigned to users or service users.
 */
export interface Role {
  /** The role id */
  id: string;
  /** The name of the role */
  display_name: string;
  /** The time the role was created */
  created_at: string;
  /** The user id that created the role. */
  created_by: string;
  /** The list of permissions associated with this role. */
  permissions: string[];
  /** True for immutable built-in roles. */
  is_system: boolean;
}
