/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { Role } from './role';

/**
 * A page of roles
 */
export interface RolePage {
  items: Role[];
  /** The page token to use to request the next page of items */
  next_page_token?: string;
}
