/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ScimGroupMapping } from './scimGroupMapping';

/**
 * The SCIM group-to-role mappings configured for an organization.
 */
export interface ScimGroupMappingPage {
  items: ScimGroupMapping[];
}
