/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The role a SCIM group's members should hold.
 */
export interface ScimGroupMappingWriteBody {
  /** The id of a role in this organization. */
  role_id: string;
}
