/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The result of an authorization resource sync operation
 */
export interface ScopeSyncResult {
  /** The number of projects synced */
  projects_synced: number;
  /** The number of environments synced */
  environments_synced: number;
  /** The number of authorization resources inserted or refreshed */
  resources_upserted: number;
}
