/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ServiceUserRole } from './serviceUserRole';

/**
 * Details required to create the service user
 */
export interface ServiceUserCreateBody {
  /**
   * A display name of the service user
   *
   * @minLength 2
   * @maxLength 200
   * @pattern ^[^\p{Cc}\p{Cs}\p{Z}\n]( |[^\p{Cc}\p{Cs}\p{Z}\n])*[^\p{Cc}\p{Cs}\p{Z}\n]$
   */
  display_name: string;
  /**
   * The expiry time in days from the time of creation
   *
   * @minimum 1
   * @maximum 3660
   */
  expiry_in_days: number;
  /** The initial set of roles to assign to this service user. These can be modified later. */
  roles?: ServiceUserRole[];
}
