/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Details required to regenerate the service user
 */
export interface ServiceUserRegenerateBody {
  /**
   * The expiry time in days from the time of regeneration
   *
   * @minimum 1
   * @maximum 3660
   */
  expiry_in_days: number;
}
