/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ServiceUser } from './serviceUser';
import type { ServiceUserWithTokenAllOf } from './serviceUserWithTokenAllOf';

export type ServiceUserWithToken = ServiceUser & ServiceUserWithTokenAllOf;
