/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A role to assign to a user or service user.
 */
export interface ServiceUserRole {
  /** The role id to assign */
  id: string;
  /** The scope to assign the role within. If not provided, the role is assigned at the organization level. */
  scope?: string;
}
