/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The result of a SpiceDB sync operation
 */
export interface SpiceDBSyncResult {
  /** The number of relationships added during the sync operation */
  added: number;
  /** The number of relationships removed during the sync operation */
  removed?: number;
}
