/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The details of a users account
 */
export interface User {
  /** The user id */
  id: string;
  /** A display name for the user */
  display_name: string;
  /** The time the user account was registered */
  created_at: string;
  /** The approximate time the user last logged in */
  last_logged_in_at?: string;
  /** The list of login providers that can be used to login to this user. */
  login_providers: string[];
  /** The primary email address if known for the current user. */
  primary_email_address?: string;
}
