/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type UserTypeQueryParamParameter =
  (typeof UserTypeQueryParamParameter)[keyof typeof UserTypeQueryParamParameter];

export const UserTypeQueryParamParameter = {
  user: 'user',
  'service-user': 'service-user',
} as const;
