/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { SubjectType } from './subjectType';

/**
 * A user membership in an org
 */
export interface UserMembership {
  /** The membership id */
  id: string;
  /** The time the membership was created */
  created_at: string;
  /** The org id of the membership */
  org_id: string;
  /** The membership subject type. */
  subject_type: SubjectType;
  /** The membership subject identity. */
  subject: string;
  /** The membership scope if applicable composed by <resource-kind>:<resource-id>. It will be empty for organization level memberships. */
  scope?: string;
}
