/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  AvailableResourceTypePage,
  InternalListResourceTypesParams,
  ListAvailableResourceTypesParams,
  ListResourceTypesParams,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
  ResourceType,
  ResourceTypeCreateBody,
  ResourceTypePage,
  ResourceTypeUpdateBody,
} from '../../../../../models/v2/controlplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List built-in resource types
 */
export const internalListResourceTypes = (
  params?: InternalListResourceTypesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourceTypePage>(
    { url: `/internal/resource-types`, method: 'GET', params, signal },
    options,
  );
};

export const getInternalListResourceTypesQueryKey = (params?: InternalListResourceTypesParams) => {
  return [`/internal/resource-types`, ...(params ? [params] : [])] as const;
};

export const getInternalListResourceTypesQueryOptions = <
  TData = Awaited<ReturnType<typeof internalListResourceTypes>>,
  TError = ErrorType<unknown>,
>(
  params?: InternalListResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalListResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInternalListResourceTypesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof internalListResourceTypes>>> = ({
    signal,
  }) => internalListResourceTypes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof internalListResourceTypes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InternalListResourceTypesQueryResult = NonNullable<
  Awaited<ReturnType<typeof internalListResourceTypes>>
>;
export type InternalListResourceTypesQueryError = ErrorType<unknown>;

export function useInternalListResourceTypes<
  TData = Awaited<ReturnType<typeof internalListResourceTypes>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | InternalListResourceTypesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalListResourceTypes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalListResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof internalListResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInternalListResourceTypes<
  TData = Awaited<ReturnType<typeof internalListResourceTypes>>,
  TError = ErrorType<unknown>,
>(
  params?: InternalListResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalListResourceTypes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalListResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof internalListResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInternalListResourceTypes<
  TData = Awaited<ReturnType<typeof internalListResourceTypes>>,
  TError = ErrorType<unknown>,
>(
  params?: InternalListResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalListResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List built-in resource types
 */

/**
 *
 */
export function useInternalListResourceTypes<
  TData = Awaited<ReturnType<typeof internalListResourceTypes>>,
  TError = ErrorType<unknown>,
>(
  params?: InternalListResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalListResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInternalListResourceTypesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new built-in resource type
 */
export const internalCreateResourceType = (
  resourceTypeCreateBody: ResourceTypeCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourceType>(
    {
      url: `/internal/resource-types`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resourceTypeCreateBody,
      signal,
    },
    options,
  );
};

export const getInternalCreateResourceTypeMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalCreateResourceType>>,
    TError,
    { data: ResourceTypeCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalCreateResourceType>>,
  TError,
  { data: ResourceTypeCreateBody },
  TContext
> => {
  const mutationKey = ['internalCreateResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalCreateResourceType>>,
    { data: ResourceTypeCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return internalCreateResourceType(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalCreateResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalCreateResourceType>>
>;
export type InternalCreateResourceTypeMutationBody = ResourceTypeCreateBody;
export type InternalCreateResourceTypeMutationError = ErrorType<
  N400BadRequestResponse | N409ConflictResponse
>;

/**
 * @summary Create a new built-in resource type
 */
export const useInternalCreateResourceType = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalCreateResourceType>>,
      TError,
      { data: ResourceTypeCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalCreateResourceType>>,
  TError,
  { data: ResourceTypeCreateBody },
  TContext
> => {
  const mutationOptions = getInternalCreateResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a built-in resource type
 */
export const internalDeleteResourceType = (
  typeId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/internal/resource-types/${typeId}`, method: 'DELETE' },
    options,
  );
};

export const getInternalDeleteResourceTypeMutationOptions = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalDeleteResourceType>>,
    TError,
    { typeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalDeleteResourceType>>,
  TError,
  { typeId: string },
  TContext
> => {
  const mutationKey = ['internalDeleteResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalDeleteResourceType>>,
    { typeId: string }
  > = (props) => {
    const { typeId } = props ?? {};

    return internalDeleteResourceType(typeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalDeleteResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalDeleteResourceType>>
>;

export type InternalDeleteResourceTypeMutationError = ErrorType<
  N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Delete a built-in resource type
 */
export const useInternalDeleteResourceType = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalDeleteResourceType>>,
      TError,
      { typeId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalDeleteResourceType>>,
  TError,
  { typeId: string },
  TContext
> => {
  const mutationOptions = getInternalDeleteResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update a built-in resource type
 */
export const internalUpdateResourceType = (
  typeId: string,
  resourceTypeUpdateBody: ResourceTypeUpdateBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResourceType>(
    {
      url: `/internal/resource-types/${typeId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: resourceTypeUpdateBody,
    },
    options,
  );
};

export const getInternalUpdateResourceTypeMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalUpdateResourceType>>,
    TError,
    { typeId: string; data: ResourceTypeUpdateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalUpdateResourceType>>,
  TError,
  { typeId: string; data: ResourceTypeUpdateBody },
  TContext
> => {
  const mutationKey = ['internalUpdateResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalUpdateResourceType>>,
    { typeId: string; data: ResourceTypeUpdateBody }
  > = (props) => {
    const { typeId, data } = props ?? {};

    return internalUpdateResourceType(typeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalUpdateResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalUpdateResourceType>>
>;
export type InternalUpdateResourceTypeMutationBody = ResourceTypeUpdateBody;
export type InternalUpdateResourceTypeMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Update a built-in resource type
 */
export const useInternalUpdateResourceType = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalUpdateResourceType>>,
      TError,
      { typeId: string; data: ResourceTypeUpdateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalUpdateResourceType>>,
  TError,
  { typeId: string; data: ResourceTypeUpdateBody },
  TContext
> => {
  const mutationOptions = getInternalUpdateResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List available resource types for an environment in project
 */
export const listAvailableResourceTypes = (
  orgId: string,
  projectId: string,
  envId: string,
  params?: ListAvailableResourceTypesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AvailableResourceTypePage>(
    {
      url: `/orgs/${orgId}/projects/${projectId}/envs/${envId}/available-resource-types`,
      method: 'GET',
      params,
      signal,
    },
    options,
  );
};

export const getListAvailableResourceTypesQueryKey = (
  orgId?: string,
  projectId?: string,
  envId?: string,
  params?: ListAvailableResourceTypesParams,
) => {
  return [
    `/orgs/${orgId}/projects/${projectId}/envs/${envId}/available-resource-types`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListAvailableResourceTypesQueryOptions = <
  TData = Awaited<ReturnType<typeof listAvailableResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  projectId: string,
  envId: string,
  params?: ListAvailableResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListAvailableResourceTypesQueryKey(orgId, projectId, envId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAvailableResourceTypes>>> = ({
    signal,
  }) => listAvailableResourceTypes(orgId, projectId, envId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && projectId && envId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type ListAvailableResourceTypesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAvailableResourceTypes>>
>;
export type ListAvailableResourceTypesQueryError = ErrorType<N404NotFoundResponse>;

export function useListAvailableResourceTypes<
  TData = Awaited<ReturnType<typeof listAvailableResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  projectId: string,
  envId: string,
  params: undefined | ListAvailableResourceTypesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAvailableResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof listAvailableResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAvailableResourceTypes<
  TData = Awaited<ReturnType<typeof listAvailableResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  projectId: string,
  envId: string,
  params?: ListAvailableResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAvailableResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof listAvailableResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAvailableResourceTypes<
  TData = Awaited<ReturnType<typeof listAvailableResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  projectId: string,
  envId: string,
  params?: ListAvailableResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List available resource types for an environment in project
 */

/**
 *
 */
export function useListAvailableResourceTypes<
  TData = Awaited<ReturnType<typeof listAvailableResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  projectId: string,
  envId: string,
  params?: ListAvailableResourceTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAvailableResourceTypes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListAvailableResourceTypesQueryOptions(
    orgId,
    projectId,
    envId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List available resource types
 */
export const listResourceTypes = (
  orgId: string,
  params?: ListResourceTypesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourceTypePage>(
    { url: `/orgs/${orgId}/resource-types`, method: 'GET', params, signal },
    options,
  );
};

export const getListResourceTypesQueryKey = (orgId?: string, params?: ListResourceTypesParams) => {
  return [`/orgs/${orgId}/resource-types`, ...(params ? [params] : [])] as const;
};

export const getListResourceTypesQueryOptions = <
  TData = Awaited<ReturnType<typeof listResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListResourceTypesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listResourceTypes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListResourceTypesQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listResourceTypes>>> = ({ signal }) =>
    listResourceTypes(orgId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listResourceTypes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListResourceTypesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listResourceTypes>>
>;
export type ListResourceTypesQueryError = ErrorType<N404NotFoundResponse>;

export function useListResourceTypes<
  TData = Awaited<ReturnType<typeof listResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params: undefined | ListResourceTypesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listResourceTypes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof listResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListResourceTypes<
  TData = Awaited<ReturnType<typeof listResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListResourceTypesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listResourceTypes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listResourceTypes>>,
          TError,
          Awaited<ReturnType<typeof listResourceTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListResourceTypes<
  TData = Awaited<ReturnType<typeof listResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListResourceTypesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listResourceTypes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List available resource types
 */

/**
 *
 */
export function useListResourceTypes<
  TData = Awaited<ReturnType<typeof listResourceTypes>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  params?: ListResourceTypesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listResourceTypes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListResourceTypesQueryOptions(orgId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new resource type
 */
export const createResourceType = (
  orgId: string,
  resourceTypeCreateBody: ResourceTypeCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourceType>(
    {
      url: `/orgs/${orgId}/resource-types`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resourceTypeCreateBody,
      signal,
    },
    options,
  );
};

export const getCreateResourceTypeMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createResourceType>>,
    TError,
    { orgId: string; data: ResourceTypeCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createResourceType>>,
  TError,
  { orgId: string; data: ResourceTypeCreateBody },
  TContext
> => {
  const mutationKey = ['createResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createResourceType>>,
    { orgId: string; data: ResourceTypeCreateBody }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return createResourceType(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createResourceType>>
>;
export type CreateResourceTypeMutationBody = ResourceTypeCreateBody;
export type CreateResourceTypeMutationError = ErrorType<
  N400BadRequestResponse | N409ConflictResponse
>;

/**
 * @summary Create a new resource type
 */
export const useCreateResourceType = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createResourceType>>,
      TError,
      { orgId: string; data: ResourceTypeCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createResourceType>>,
  TError,
  { orgId: string; data: ResourceTypeCreateBody },
  TContext
> => {
  const mutationOptions = getCreateResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a resource type
 */
export const deleteResourceType = (
  orgId: string,
  typeId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/orgs/${orgId}/resource-types/${typeId}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteResourceTypeMutationOptions = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteResourceType>>,
    TError,
    { orgId: string; typeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteResourceType>>,
  TError,
  { orgId: string; typeId: string },
  TContext
> => {
  const mutationKey = ['deleteResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteResourceType>>,
    { orgId: string; typeId: string }
  > = (props) => {
    const { orgId, typeId } = props ?? {};

    return deleteResourceType(orgId, typeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteResourceType>>
>;

export type DeleteResourceTypeMutationError = ErrorType<
  N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Delete a resource type
 */
export const useDeleteResourceType = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteResourceType>>,
      TError,
      { orgId: string; typeId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteResourceType>>,
  TError,
  { orgId: string; typeId: string },
  TContext
> => {
  const mutationOptions = getDeleteResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a resource type
 */
export const getResourceType = (
  orgId: string,
  typeId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourceType>(
    { url: `/orgs/${orgId}/resource-types/${typeId}`, method: 'GET', signal },
    options,
  );
};

export const getGetResourceTypeQueryKey = (orgId?: string, typeId?: string) => {
  return [`/orgs/${orgId}/resource-types/${typeId}`] as const;
};

export const getGetResourceTypeQueryOptions = <
  TData = Awaited<ReturnType<typeof getResourceType>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  typeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceType>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetResourceTypeQueryKey(orgId, typeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getResourceType>>> = ({ signal }) =>
    getResourceType(orgId, typeId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!(orgId && typeId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getResourceType>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetResourceTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getResourceType>>>;
export type GetResourceTypeQueryError = ErrorType<N404NotFoundResponse>;

export function useGetResourceType<
  TData = Awaited<ReturnType<typeof getResourceType>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  typeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceType>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResourceType>>,
          TError,
          Awaited<ReturnType<typeof getResourceType>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetResourceType<
  TData = Awaited<ReturnType<typeof getResourceType>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  typeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceType>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResourceType>>,
          TError,
          Awaited<ReturnType<typeof getResourceType>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetResourceType<
  TData = Awaited<ReturnType<typeof getResourceType>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  typeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceType>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a resource type
 */

/**
 *
 */
export function useGetResourceType<
  TData = Awaited<ReturnType<typeof getResourceType>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  typeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceType>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetResourceTypeQueryOptions(orgId, typeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a resource type
 */
export const updateResourceType = (
  orgId: string,
  typeId: string,
  resourceTypeUpdateBody: ResourceTypeUpdateBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResourceType>(
    {
      url: `/orgs/${orgId}/resource-types/${typeId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: resourceTypeUpdateBody,
    },
    options,
  );
};

export const getUpdateResourceTypeMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateResourceType>>,
    TError,
    { orgId: string; typeId: string; data: ResourceTypeUpdateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateResourceType>>,
  TError,
  { orgId: string; typeId: string; data: ResourceTypeUpdateBody },
  TContext
> => {
  const mutationKey = ['updateResourceType'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateResourceType>>,
    { orgId: string; typeId: string; data: ResourceTypeUpdateBody }
  > = (props) => {
    const { orgId, typeId, data } = props ?? {};

    return updateResourceType(orgId, typeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateResourceTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateResourceType>>
>;
export type UpdateResourceTypeMutationBody = ResourceTypeUpdateBody;
export type UpdateResourceTypeMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Update a resource type
 */
export const useUpdateResourceType = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateResourceType>>,
      TError,
      { orgId: string; typeId: string; data: ResourceTypeUpdateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateResourceType>>,
  TError,
  { orgId: string; typeId: string; data: ResourceTypeUpdateBody },
  TContext
> => {
  const mutationOptions = getUpdateResourceTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
