/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type { N401UnauthorizedResponse, TemporaryLoginBody } from '../../../../../models/v2/iam';

/**
 * @summary Login to the orchestrator (temporary)
 */
export const temporaryLogin = (temporaryLoginBody: TemporaryLoginBody, signal?: AbortSignal) => {
  return customInstance<null>({
    url: `/temporary-login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: temporaryLoginBody,
    signal,
  });
};

export const getTemporaryLoginMutationOptions = <
  TError = ErrorType<N401UnauthorizedResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof temporaryLogin>>,
    TError,
    { data: TemporaryLoginBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof temporaryLogin>>,
  TError,
  { data: TemporaryLoginBody },
  TContext
> => {
  const mutationKey = ['temporaryLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof temporaryLogin>>,
    { data: TemporaryLoginBody }
  > = (props) => {
    const { data } = props ?? {};

    return temporaryLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TemporaryLoginMutationResult = NonNullable<Awaited<ReturnType<typeof temporaryLogin>>>;
export type TemporaryLoginMutationBody = TemporaryLoginBody;
export type TemporaryLoginMutationError = ErrorType<N401UnauthorizedResponse>;

/**
 * @summary Login to the orchestrator (temporary)
 */
export const useTemporaryLogin = <TError = ErrorType<N401UnauthorizedResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof temporaryLogin>>,
      TError,
      { data: TemporaryLoginBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof temporaryLogin>>,
  TError,
  { data: TemporaryLoginBody },
  TContext
> => {
  const mutationOptions = getTemporaryLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Logout from the orchestrator
 */
export const logout = (signal?: AbortSignal) => {
  return customInstance<null>({ url: `/logout`, method: 'POST', signal });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
  const mutationKey = ['logout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
    return logout();
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout from the orchestrator
 */
export const useLogout = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
