/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import { delay, http, HttpResponse } from 'msw';

import type { N401UnauthorizedResponse } from '../../../../../models/v2/iam';

export const getTemporaryLoginResponseMock401 = (
  overrideResponse: Partial<N401UnauthorizedResponse> = {},
): N401UnauthorizedResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getTemporaryLoginMockHandler = (
  overrideResponse?:
    | null
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<null> | null),
) => {
  return http.post('http://localhost:8080/temporary-login', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};

export const getTemporaryLoginMockHandler204 = (
  overrideResponse?:
    | null
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<null> | null),
) => {
  return http.post('http://localhost:8080/temporary-login', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};

export const getTemporaryLoginMockHandler401 = (
  overrideResponse?:
    | N401UnauthorizedResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N401UnauthorizedResponse> | N401UnauthorizedResponse),
) => {
  return http.post('http://localhost:8080/temporary-login', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getTemporaryLoginResponseMock401(),
      ),
      { status: 401, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getLogoutMockHandler = (
  overrideResponse?:
    | null
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<null> | null),
) => {
  return http.post('http://localhost:8080/logout', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};

export const getLogoutMockHandler204 = (
  overrideResponse?:
    | null
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<null> | null),
) => {
  return http.post('http://localhost:8080/logout', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};
export const getPublicMock = () => [getTemporaryLoginMockHandler(), getLogoutMockHandler()];
