/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  CurrentUser,
  DismissPromptParams,
  ListUserSessionTokensParams,
  N400BadRequestResponse,
  N403ForbiddenResponse,
  N404NotFoundResponse,
  ResourcePermissionCheck,
  ResourcePermissionCheckResult,
  UserSessionTokenPage,
} from '../../../../../models/v2/iam';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Bulkly check permissions for the current subject that is logged in. This works for both human users and service users.
 */
export const checkPermissions = (
  resourcePermissionCheck: ResourcePermissionCheck[],
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResourcePermissionCheckResult>(
    {
      url: `/auth/check-permissions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resourcePermissionCheck,
      signal,
    },
    options,
  );
};

export const getCheckPermissionsQueryKey = (
  resourcePermissionCheck?: ResourcePermissionCheck[],
) => {
  return [`/auth/check-permissions`, resourcePermissionCheck] as const;
};

export const getCheckPermissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof checkPermissions>>,
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse>,
>(
  resourcePermissionCheck: ResourcePermissionCheck[],
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCheckPermissionsQueryKey(resourcePermissionCheck);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof checkPermissions>>> = ({ signal }) =>
    checkPermissions(resourcePermissionCheck, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof checkPermissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CheckPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof checkPermissions>>>;
export type CheckPermissionsQueryError = ErrorType<
  N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse
>;

export function useCheckPermissions<
  TData = Awaited<ReturnType<typeof checkPermissions>>,
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse>,
>(
  resourcePermissionCheck: ResourcePermissionCheck[],
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkPermissions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkPermissions>>,
          TError,
          Awaited<ReturnType<typeof checkPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCheckPermissions<
  TData = Awaited<ReturnType<typeof checkPermissions>>,
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse>,
>(
  resourcePermissionCheck: ResourcePermissionCheck[],
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkPermissions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkPermissions>>,
          TError,
          Awaited<ReturnType<typeof checkPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCheckPermissions<
  TData = Awaited<ReturnType<typeof checkPermissions>>,
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse>,
>(
  resourcePermissionCheck: ResourcePermissionCheck[],
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Bulkly check permissions for the current subject that is logged in. This works for both human users and service users.
 */

/**
 *
 */
export function useCheckPermissions<
  TData = Awaited<ReturnType<typeof checkPermissions>>,
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse | N404NotFoundResponse>,
>(
  resourcePermissionCheck: ResourcePermissionCheck[],
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCheckPermissionsQueryOptions(resourcePermissionCheck, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List all of the active user session tokens
 */
export const listUserSessionTokens = (
  userId: string,
  params?: ListUserSessionTokensParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserSessionTokenPage>(
    { url: `/users/${userId}/session-tokens`, method: 'GET', params, signal },
    options,
  );
};

export const getListUserSessionTokensQueryKey = (
  userId?: string,
  params?: ListUserSessionTokensParams,
) => {
  return [`/users/${userId}/session-tokens`, ...(params ? [params] : [])] as const;
};

export const getListUserSessionTokensQueryOptions = <
  TData = Awaited<ReturnType<typeof listUserSessionTokens>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: ListUserSessionTokensParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserSessionTokens>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListUserSessionTokensQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserSessionTokens>>> = ({ signal }) =>
    listUserSessionTokens(userId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!userId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUserSessionTokens>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUserSessionTokensQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUserSessionTokens>>
>;
export type ListUserSessionTokensQueryError = ErrorType<unknown>;

export function useListUserSessionTokens<
  TData = Awaited<ReturnType<typeof listUserSessionTokens>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | ListUserSessionTokensParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserSessionTokens>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserSessionTokens>>,
          TError,
          Awaited<ReturnType<typeof listUserSessionTokens>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserSessionTokens<
  TData = Awaited<ReturnType<typeof listUserSessionTokens>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: ListUserSessionTokensParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserSessionTokens>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserSessionTokens>>,
          TError,
          Awaited<ReturnType<typeof listUserSessionTokens>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListUserSessionTokens<
  TData = Awaited<ReturnType<typeof listUserSessionTokens>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: ListUserSessionTokensParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserSessionTokens>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all of the active user session tokens
 */

/**
 *
 */
export function useListUserSessionTokens<
  TData = Awaited<ReturnType<typeof listUserSessionTokens>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: ListUserSessionTokensParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listUserSessionTokens>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListUserSessionTokensQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Revoke the session token for this user. Due to internal caching, this may take up to a minute for authorized sessions to be revoked.
 */
export const revokeUserSessionToken = (
  userId: string,
  hash: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/users/${userId}/session-tokens/${hash}`, method: 'DELETE' },
    options,
  );
};

export const getRevokeUserSessionTokenMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeUserSessionToken>>,
    TError,
    { userId: string; hash: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeUserSessionToken>>,
  TError,
  { userId: string; hash: string },
  TContext
> => {
  const mutationKey = ['revokeUserSessionToken'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeUserSessionToken>>,
    { userId: string; hash: string }
  > = (props) => {
    const { userId, hash } = props ?? {};

    return revokeUserSessionToken(userId, hash, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeUserSessionTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeUserSessionToken>>
>;

export type RevokeUserSessionTokenMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Revoke the session token for this user. Due to internal caching, this may take up to a minute for authorized sessions to be revoked.
 */
export const useRevokeUserSessionToken = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeUserSessionToken>>,
      TError,
      { userId: string; hash: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeUserSessionToken>>,
  TError,
  { userId: string; hash: string },
  TContext
> => {
  const mutationOptions = getRevokeUserSessionTokenMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Dismiss a prompt for the user
 */
export const dismissPrompt = (
  userId: string,
  params: DismissPromptParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/users/${userId}/actions/dismiss-prompt`, method: 'POST', params, signal },
    options,
  );
};

export const getDismissPromptMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dismissPrompt>>,
    TError,
    { userId: string; params: DismissPromptParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dismissPrompt>>,
  TError,
  { userId: string; params: DismissPromptParams },
  TContext
> => {
  const mutationKey = ['dismissPrompt'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dismissPrompt>>,
    { userId: string; params: DismissPromptParams }
  > = (props) => {
    const { userId, params } = props ?? {};

    return dismissPrompt(userId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DismissPromptMutationResult = NonNullable<Awaited<ReturnType<typeof dismissPrompt>>>;

export type DismissPromptMutationError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>;

/**
 * @summary Dismiss a prompt for the user
 */
export const useDismissPrompt = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dismissPrompt>>,
      TError,
      { userId: string; params: DismissPromptParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dismissPrompt>>,
  TError,
  { userId: string; params: DismissPromptParams },
  TContext
> => {
  const mutationOptions = getDismissPromptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get details of the current user that is logged in
 */
export const getCurrentUser = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CurrentUser>({ url: `/current-user`, method: 'GET', signal }, options);
};

export const getGetCurrentUserQueryKey = () => {
  return [`/current-user`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) =>
    getCurrentUser(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError = ErrorType<unknown>;

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get details of the current user that is logged in
 */

/**
 *
 */
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
