/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type CalculateDeploymentDiffParams = {
  /**
   * The id of the previous deployment in the same environment. If this is not specified, the diff
will be calculated from the previous stateful deployment.
   
   */
  fromDeploymentId?: string;
};
