/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Details about the Terraform resources added / removed / changed .
 */
export interface DeploymentTFResourceCounts {
  /** Number of Terraform resources involved in the deployment. */
  num_resources: number;
  /** Number of Terraform resources added by this deployment run. */
  num_resources_added: number;
  /** Number of Terraform resources removed by this deployment run. */
  num_resources_removed: number;
  /** Number of Terraform resources changed by this deployment run. */
  num_resources_changed: number;
}
