/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { DeploymentDiff } from './deploymentDiff';

export interface DeploymentDryRun {
  /** The Runner ID that this deployment would have executed on */
  runner_id: string;
  diff: DeploymentDiff;
}
