/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Exact canonical SemVer selections by Module slug. Proposed versions require the scoped module.version.use-proposed capability.
 */
export type DeploymentCreateBodyModuleVersions = { [key: string]: string };
