/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The type of change in a resource node.
 */
export type DeploymentDiffChangeType =
  (typeof DeploymentDiffChangeType)[keyof typeof DeploymentDiffChangeType];

export const DeploymentDiffChangeType = {
  DeploymentDiffChangeTypeAdded: 'added',
  DeploymentDiffChangeTypeRemoved: 'removed',
  DeploymentDiffChangeTypeModuleChanged: 'module_changed',
  DeploymentDiffChangeTypeParamsChanged: 'params_changed',
} as const;
