/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { DeploymentDiffChangeType } from './deploymentDiffChangeType';

export interface DeploymentDiffChange {
  /** The deterministic hash of the node. */
  id: string;
  /** The resource identifier of the node including the type, class, and id */
  resource: string;
  /** The type of change in a resource node. */
  type: DeploymentDiffChangeType;
  /** A human readable summary of the change to this node. */
  summary: string;
}
