/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Optional parameters to pass to the resource provisioning.
 *
 * @maxItems 20
 */
export type DeploymentManifestResourceParams = { [key: string]: unknown };
