/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { DeploymentResultMetadataPerNode } from './deploymentResultMetadataPerNode';

/**
 * The metadata produced by the resources involved in the deployment.
 */
export type DeploymentResultMetadata = DeploymentResultMetadataPerNode[];
