/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Parameter variables is deprecated and will be removed in a future release. Please use outputs instead.
 *
 * @deprecated
 * @maxItems 100
 */
export type DeploymentManifestWorkloadVariables = { [key: string]: string };
