/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { DeploymentManifestResourceParams } from './deploymentManifestResourceParams';
import type { ResourceClass } from './resourceClass';
import type { ResourceId } from './resourceId';

/**
 * A resource to provision as part of the deployment
 */
export interface DeploymentManifestResource {
  /**
   * The resource type to provision
   *
   * @minLength 2
   * @maxLength 63
   * @pattern ^[A-Za-z0-9][A-Za-z0-9-]{0,61}[A-Za-z0-9]$
   */
  type: string;
  class?: ResourceClass;
  id?: ResourceId;
  /**
   * Optional parameters to pass to the resource provisioning.
   *
   * @maxItems 20
   */
  params?: DeploymentManifestResourceParams;
}
