/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Metrics resulting from a deployment.
 */
export interface DeploymentMetrics {
  /** The number of workloads in the deployment. */
  num_workloads: number;
  /** The number of resource nodes in the graph. */
  num_resource_nodes: number;
  /** The number of terraformed resources. Only known after deployment. */
  num_tf_resources?: number;
  /** The number of terraformed resources added. Only known after deployment. */
  num_tf_resources_added?: number;
  /** The number of terraformed resources removed. Only known after deployment. */
  num_tf_resources_removed?: number;
  /** The number of terraformed resources changed. Only known after deployment. */
  num_tf_resources_changed?: number;
}
