/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export interface InternalModuleUsageItem {
  project_id: string;
  env_id: string;
  environment_uuid: string;
  module_version: string;
  deployment_id: string;
  observed_at: string;
}
