/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { EnvIdQueryParamParameter } from './envIdQueryParamParameter';
import type { ProjectIdQueryParamParameter } from './projectIdQueryParamParameter';

export type InternalDeleteDeploymentsParams = {
  /**
   * The Project ID
   */
  project_id?: ProjectIdQueryParamParameter;
  /**
   * The Environment ID
   */
  env_id?: EnvIdQueryParamParameter;
  /**
   * Whether to ignore the requirement for the last deployment to be a successful destroy. This should only be used in exceptional circumstances.
   */
  force?: boolean;
};
