/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { InternalModuleUsageEnvIdsByProjectId } from './internalModuleUsageEnvIdsByProjectId';

export interface InternalModuleUsage {
  env_ids_by_project_id: InternalModuleUsageEnvIdsByProjectId;
}
