/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { EnvIdQueryParamParameter } from './envIdQueryParamParameter';
import type { ProjectIdQueryParamParameter } from './projectIdQueryParamParameter';

export type ListActiveResourceNodesParams = {
  /**
   * The Project ID
   */
  project_id?: ProjectIdQueryParamParameter;
  /**
   * The Environment ID
   */
  env_id?: EnvIdQueryParamParameter;
};
