/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { MetadataKeySchema } from './metadataKeySchema';

/**
 * A metadata key for an organization.
 */
export interface MetadataKeyCreateBody {
  /**
   * The name of the metadata key.
   *
   * @pattern ^[A-Z][a-zA-Z0-9]*(-[A-Z0-9][a-zA-Z0-9]*)*$
   */
  name: string;
  /** A human-readable description of the metadata key. */
  description?: string;
  schema: MetadataKeySchema;
}
