/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { MetadataKeySchemaType } from './metadataKeySchemaType';

/**
 * The schema of the metadata key.
 */
export interface MetadataKeySchema {
  /** The type of the metadata key. */
  type: MetadataKeySchemaType;
  /** The format of the metadata key. */
  format?: string;
  /** A regular expression pattern for the metadata key. */
  pattern?: string;
}
