/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { MetadataKey } from './metadataKey';

/**
 * A page of metadata keys
 */
export interface MetadataKeyPage {
  items: MetadataKey[];
  /** The page token to use to request the next page of items */
  next_page_token?: string;
}
