/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { RemoteRunnerMessageCreateJobAction } from './remoteRunnerMessageCreateJobAction';
import type { RemoteRunnerMessageCreateJobConfiguration } from './remoteRunnerMessageCreateJobConfiguration';

/**
 * The response for creating a job on the runner.
 */
export interface RemoteRunnerMessageCreateJob {
  action: RemoteRunnerMessageCreateJobAction;
  /** The ID of the job created on the runner. */
  job_id: string;
  /** The ID of the namespace associated with the job. */
  namespace: string;
  /** The configuration for the job to be created on the runner. It must be parsable into a kubernetes Job definition. */
  configuration: RemoteRunnerMessageCreateJobConfiguration;
  /** The deployment token to authenticate any request to update deployment results from the remote runner. */
  deployment_token: string;
}
