/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */
import type { RemoteRunnerMessageGetJobStatusAction } from './remoteRunnerMessageGetJobStatusAction';

/**
 * The response for getting the status of a job on the runner.
 */
export interface RemoteRunnerMessageGetJobStatus {
  action: RemoteRunnerMessageGetJobStatusAction;
  /** The ID of the job whose status is being requested. */
  job_id: string;
  /** The ID of the namespace associated with the job. */
  namespace: string;
  /** The deployment token to authenticate any request to update deployment results from the remote runner. */
  deployment_token: string;
}
