/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The configuration for the job to be created on the runner. It must be parsable into a kubernetes Job definition.
 */
export type RemoteRunnerMessageCreateJobConfiguration = { [key: string]: unknown };
