/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */

export type RemoteRunnerMessageGetJobStatusAction =
  (typeof RemoteRunnerMessageGetJobStatusAction)[keyof typeof RemoteRunnerMessageGetJobStatusAction];

export const RemoteRunnerMessageGetJobStatusAction = {
  'get-job-status': 'get-job-status',
} as const;
