/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type WaitForDeploymentCompleteParams = {
  /**
   * Sets a maximum timeout before the HTTP-408 response is returned.
   *
   * @minimum 2
   */
  timeout_in_seconds?: number;
};
