/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  N401UnauthorizedResponse,
  N403ForbiddenResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
  Organization,
} from '../../../../../models/v2/controlplane';

export const getCreateOrganizationResponseMock = (
  overrideResponse: Partial<Organization> = {},
): Organization => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  uuid: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  created_by: faker.string.uuid(),
  updated_at: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split('.')[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
  plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getCreateOrganizationResponseMock201 = (
  overrideResponse: Partial<Organization> = {},
): Organization => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  uuid: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  created_by: faker.string.uuid(),
  updated_at: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split('.')[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
  plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getCreateOrganizationResponseMock401 = (
  overrideResponse: Partial<N401UnauthorizedResponse> = {},
): N401UnauthorizedResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateOrganizationResponseMock403 = (
  overrideResponse: Partial<N403ForbiddenResponse> = {},
): N403ForbiddenResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateOrganizationResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetOrganizationResponseMock = (
  overrideResponse: Partial<Organization> = {},
): Organization => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  uuid: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  created_by: faker.string.uuid(),
  updated_at: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split('.')[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
  plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetOrganizationResponseMock200 = (
  overrideResponse: Partial<Organization> = {},
): Organization => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  uuid: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  created_by: faker.string.uuid(),
  updated_at: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split('.')[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement(['active', 'deleting', 'delete_failed', 'deleted'] as const),
  plan: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetOrganizationResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateOrganizationMockHandler = (
  overrideResponse?:
    | Organization
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Organization> | Organization),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOrganizationResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateOrganizationMockHandler201 = (
  overrideResponse?:
    | Organization
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Organization> | Organization),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOrganizationResponseMock201(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateOrganizationMockHandler401 = (
  overrideResponse?:
    | N401UnauthorizedResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N401UnauthorizedResponse> | N401UnauthorizedResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOrganizationResponseMock401(),
        ),
        { status: 401, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateOrganizationMockHandler403 = (
  overrideResponse?:
    | N403ForbiddenResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N403ForbiddenResponse> | N403ForbiddenResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOrganizationResponseMock403(),
        ),
        { status: 403, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateOrganizationMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateOrganizationResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetOrganizationMockHandler = (
  overrideResponse?:
    | Organization
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Organization> | Organization),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetOrganizationResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetOrganizationMockHandler200 = (
  overrideResponse?:
    | Organization
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Organization> | Organization),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetOrganizationResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetOrganizationMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetOrganizationResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getOrganizationMock = () => [
  getCreateOrganizationMockHandler(),
  getGetOrganizationMockHandler(),
];
