/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
  Sandbox,
  SandboxCreateBody,
} from '../../../../../models/v2/controlplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new sandbox
 */
export const createSandbox = (
  sandboxCreateBody: SandboxCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Sandbox>(
    {
      url: `/sandboxes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sandboxCreateBody,
      signal,
    },
    options,
  );
};

export const getCreateSandboxMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSandbox>>,
    TError,
    { data: SandboxCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: SandboxCreateBody },
  TContext
> => {
  const mutationKey = ['createSandbox'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSandbox>>,
    { data: SandboxCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return createSandbox(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSandboxMutationResult = NonNullable<Awaited<ReturnType<typeof createSandbox>>>;
export type CreateSandboxMutationBody = SandboxCreateBody;
export type CreateSandboxMutationError = ErrorType<N400BadRequestResponse | N409ConflictResponse>;

/**
 * @summary Create a new sandbox
 */
export const useCreateSandbox = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSandbox>>,
      TError,
      { data: SandboxCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: SandboxCreateBody },
  TContext
> => {
  const mutationOptions = getCreateSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get sandbox
 */
export const getSandbox = (
  sandboxId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Sandbox>(
    { url: `/sandboxes/${sandboxId}`, method: 'GET', signal },
    options,
  );
};

export const getGetSandboxQueryKey = (sandboxId?: string) => {
  return [`/sandboxes/${sandboxId}`] as const;
};

export const getGetSandboxQueryOptions = <
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  sandboxId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSandboxQueryKey(sandboxId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSandbox>>> = ({ signal }) =>
    getSandbox(sandboxId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!sandboxId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSandbox>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSandboxQueryResult = NonNullable<Awaited<ReturnType<typeof getSandbox>>>;
export type GetSandboxQueryError = ErrorType<N404NotFoundResponse>;

export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  sandboxId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSandbox>>,
          TError,
          Awaited<ReturnType<typeof getSandbox>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  sandboxId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSandbox>>,
          TError,
          Awaited<ReturnType<typeof getSandbox>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  sandboxId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get sandbox
 */

/**
 *
 */
export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  sandboxId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSandboxQueryOptions(sandboxId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete sandbox
 */
export const deleteSandbox = (
  sandboxId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>({ url: `/sandboxes/${sandboxId}`, method: 'DELETE' }, options);
};

export const getDeleteSandboxMutationOptions = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSandbox>>,
    TError,
    { sandboxId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSandbox>>,
  TError,
  { sandboxId: string },
  TContext
> => {
  const mutationKey = ['deleteSandbox'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSandbox>>,
    { sandboxId: string }
  > = (props) => {
    const { sandboxId } = props ?? {};

    return deleteSandbox(sandboxId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSandboxMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSandbox>>>;

export type DeleteSandboxMutationError = ErrorType<N404NotFoundResponse>;

/**
 * @summary Delete sandbox
 */
export const useDeleteSandbox = <TError = ErrorType<N404NotFoundResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSandbox>>,
      TError,
      { sandboxId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSandbox>>,
  TError,
  { sandboxId: string },
  TContext
> => {
  const mutationOptions = getDeleteSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
