/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
  Sandbox,
} from '../../../../../models/v2/controlplane';

export const getCreateSandboxResponseMock = (): Sandbox => ({
  ...{ org_id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...{
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inputs: {
      [faker.string.alphanumeric(5)]: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    completed_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
  },
});

export const getCreateSandboxResponseMock201 = (): Sandbox => ({
  ...{ org_id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...{
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inputs: {
      [faker.string.alphanumeric(5)]: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    completed_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
  },
});

export const getCreateSandboxResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateSandboxResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetSandboxResponseMock = (): Sandbox => ({
  ...{ org_id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...{
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inputs: {
      [faker.string.alphanumeric(5)]: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    completed_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
  },
});

export const getGetSandboxResponseMock200 = (): Sandbox => ({
  ...{ org_id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  ...{
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inputs: {
      [faker.string.alphanumeric(5)]: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    completed_at: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      undefined,
    ]),
  },
});

export const getGetSandboxResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getDeleteSandboxResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateSandboxMockHandler = (
  overrideResponse?:
    | Sandbox
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Sandbox> | Sandbox),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/sandboxes',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateSandboxResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateSandboxMockHandler201 = (
  overrideResponse?:
    | Sandbox
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Sandbox> | Sandbox),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/sandboxes',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateSandboxResponseMock201(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateSandboxMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/sandboxes',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateSandboxResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateSandboxMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/sandboxes',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateSandboxResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetSandboxMockHandler = (
  overrideResponse?:
    | Sandbox
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Sandbox> | Sandbox),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetSandboxResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetSandboxMockHandler200 = (
  overrideResponse?:
    | Sandbox
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Sandbox> | Sandbox),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetSandboxResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetSandboxMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetSandboxResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteSandboxMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteSandboxMockHandler204 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteSandboxMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/sandboxes/:sandboxId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteSandboxResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getSandboxMock = () => [
  getCreateSandboxMockHandler(),
  getGetSandboxMockHandler(),
  getDeleteSandboxMockHandler(),
];
