/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  N400BadRequestResponse,
  N404NotFoundResponse,
  ScimGroupMapping,
  ScimGroupMappingPage,
} from '../../../../../models/v2/iam';

export const getListScimGroupMappingsResponseMock = (
  overrideResponse: Partial<ScimGroupMappingPage> = {},
): ScimGroupMappingPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    group_display_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role_id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  })),
  ...overrideResponse,
});

export const getListScimGroupMappingsResponseMock200 = (
  overrideResponse: Partial<ScimGroupMappingPage> = {},
): ScimGroupMappingPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    group_display_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role_id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  })),
  ...overrideResponse,
});

export const getUpsertScimGroupMappingResponseMock = (
  overrideResponse: Partial<ScimGroupMapping> = {},
): ScimGroupMapping => ({
  group_display_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role_id: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse,
});

export const getUpsertScimGroupMappingResponseMock200 = (
  overrideResponse: Partial<ScimGroupMapping> = {},
): ScimGroupMapping => ({
  group_display_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role_id: faker.string.uuid(),
  created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse,
});

export const getUpsertScimGroupMappingResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getUpsertScimGroupMappingResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getDeleteScimGroupMappingResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getListScimGroupMappingsMockHandler = (
  overrideResponse?:
    | ScimGroupMappingPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ScimGroupMappingPage> | ScimGroupMappingPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/scim/group-mappings',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListScimGroupMappingsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getListScimGroupMappingsMockHandler200 = (
  overrideResponse?:
    | ScimGroupMappingPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ScimGroupMappingPage> | ScimGroupMappingPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/scim/group-mappings',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListScimGroupMappingsResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpsertScimGroupMappingMockHandler = (
  overrideResponse?:
    | ScimGroupMapping
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ScimGroupMapping> | ScimGroupMapping),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpsertScimGroupMappingResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpsertScimGroupMappingMockHandler200 = (
  overrideResponse?:
    | ScimGroupMapping
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ScimGroupMapping> | ScimGroupMapping),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpsertScimGroupMappingResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpsertScimGroupMappingMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpsertScimGroupMappingResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpsertScimGroupMappingMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpsertScimGroupMappingResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteScimGroupMappingMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteScimGroupMappingMockHandler204 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteScimGroupMappingMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/scim/group-mappings/:groupDisplayName',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteScimGroupMappingResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getProvisioningMock = () => [
  getListScimGroupMappingsMockHandler(),
  getUpsertScimGroupMappingMockHandler(),
  getDeleteScimGroupMappingMockHandler(),
];
