/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  GetSsoCallbackParams,
  InternalAuthorizeBody,
  InternalMembershipCreateBody,
  LoginUserBody,
  N400BadRequestResponse,
  N401UnauthorizedResponse,
  N403ForbiddenResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
  OrgMembership,
  RegisteredUser,
  RegisterUserBody,
  ScopeSyncResult,
  SsoConfiguration,
  SsoLoginCreateBody,
  SsoLoginResponse,
  User,
} from '../../../../../models/v2/iam';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Register a new user using a login provider and grant an initial session token in the cookie.
 */
export const registerUser = (
  registerUserBody: RegisterUserBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RegisteredUser>(
    {
      url: `/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerUserBody,
      signal,
    },
    options,
  );
};

export const getRegisterUserMutationOptions = <
  TError = ErrorType<N400BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: RegisterUserBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: RegisterUserBody },
  TContext
> => {
  const mutationKey = ['registerUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: RegisterUserBody }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>;
export type RegisterUserMutationBody = RegisterUserBody;
export type RegisterUserMutationError = ErrorType<N400BadRequestResponse>;

/**
 * @summary Register a new user using a login provider and grant an initial session token in the cookie.
 */
export const useRegisterUser = <TError = ErrorType<N400BadRequestResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerUser>>,
      TError,
      { data: RegisterUserBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: RegisterUserBody },
  TContext
> => {
  const mutationOptions = getRegisterUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Log in and create a new session token
 */
export const loginSession = (
  loginUserBody: LoginUserBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<User>(
    {
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginUserBody,
      signal,
    },
    options,
  );
};

export const getLoginSessionMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginSession>>,
    TError,
    { data: LoginUserBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginSession>>,
  TError,
  { data: LoginUserBody },
  TContext
> => {
  const mutationKey = ['loginSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginSession>>,
    { data: LoginUserBody }
  > = (props) => {
    const { data } = props ?? {};

    return loginSession(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginSessionMutationResult = NonNullable<Awaited<ReturnType<typeof loginSession>>>;
export type LoginSessionMutationBody = LoginUserBody;
export type LoginSessionMutationError = ErrorType<
  N400BadRequestResponse | N401UnauthorizedResponse
>;

/**
 * @summary Log in and create a new session token
 */
export const useLoginSession = <
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginSession>>,
      TError,
      { data: LoginUserBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginSession>>,
  TError,
  { data: LoginUserBody },
  TContext
> => {
  const mutationOptions = getLoginSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Begin SSO login flow
 */
export const requestSsoLogin = (
  ssoLoginCreateBody: SsoLoginCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SsoLoginResponse>(
    {
      url: `/auth/sso/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: ssoLoginCreateBody,
      signal,
    },
    options,
  );
};

export const getRequestSsoLoginMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestSsoLogin>>,
    TError,
    { data: SsoLoginCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestSsoLogin>>,
  TError,
  { data: SsoLoginCreateBody },
  TContext
> => {
  const mutationKey = ['requestSsoLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestSsoLogin>>,
    { data: SsoLoginCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return requestSsoLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestSsoLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestSsoLogin>>
>;
export type RequestSsoLoginMutationBody = SsoLoginCreateBody;
export type RequestSsoLoginMutationError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>;

/**
 * @summary Begin SSO login flow
 */
export const useRequestSsoLogin = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestSsoLogin>>,
      TError,
      { data: SsoLoginCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestSsoLogin>>,
  TError,
  { data: SsoLoginCreateBody },
  TContext
> => {
  const mutationOptions = getRequestSsoLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Callback SSO login flow
 */
export const getSsoCallback = (
  params?: GetSsoCallbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<User>(
    { url: `/auth/sso/callback`, method: 'GET', params, signal },
    options,
  );
};

export const getGetSsoCallbackQueryKey = (params?: GetSsoCallbackParams) => {
  return [`/auth/sso/callback`, ...(params ? [params] : [])] as const;
};

export const getGetSsoCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof getSsoCallback>>,
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
>(
  params?: GetSsoCallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSsoCallback>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSsoCallbackQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSsoCallback>>> = ({ signal }) =>
    getSsoCallback(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSsoCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSsoCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getSsoCallback>>>;
export type GetSsoCallbackQueryError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>;

export function useGetSsoCallback<
  TData = Awaited<ReturnType<typeof getSsoCallback>>,
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
>(
  params: undefined | GetSsoCallbackParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSsoCallback>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSsoCallback>>,
          TError,
          Awaited<ReturnType<typeof getSsoCallback>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSsoCallback<
  TData = Awaited<ReturnType<typeof getSsoCallback>>,
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
>(
  params?: GetSsoCallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSsoCallback>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSsoCallback>>,
          TError,
          Awaited<ReturnType<typeof getSsoCallback>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSsoCallback<
  TData = Awaited<ReturnType<typeof getSsoCallback>>,
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
>(
  params?: GetSsoCallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSsoCallback>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Callback SSO login flow
 */

/**
 *
 */
export function useGetSsoCallback<
  TData = Awaited<ReturnType<typeof getSsoCallback>>,
  TError = ErrorType<N400BadRequestResponse | N401UnauthorizedResponse>,
>(
  params?: GetSsoCallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSsoCallback>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSsoCallbackQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update SSO configuration for the organization
 */
export const internalUpdateSsoConfiguration = (
  orgId: string,
  ssoConfiguration: SsoConfiguration,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SsoConfiguration>(
    {
      url: `/internal/orgs/${orgId}/sso-configuration`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: ssoConfiguration,
    },
    options,
  );
};

export const getInternalUpdateSsoConfigurationMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>,
    TError,
    { orgId: string; data: SsoConfiguration },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>,
  TError,
  { orgId: string; data: SsoConfiguration },
  TContext
> => {
  const mutationKey = ['internalUpdateSsoConfiguration'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>,
    { orgId: string; data: SsoConfiguration }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return internalUpdateSsoConfiguration(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalUpdateSsoConfigurationMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>
>;
export type InternalUpdateSsoConfigurationMutationBody = SsoConfiguration;
export type InternalUpdateSsoConfigurationMutationError = ErrorType<
  N400BadRequestResponse | N409ConflictResponse
>;

/**
 * @summary Update SSO configuration for the organization
 */
export const useInternalUpdateSsoConfiguration = <
  TError = ErrorType<N400BadRequestResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>,
      TError,
      { orgId: string; data: SsoConfiguration },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalUpdateSsoConfiguration>>,
  TError,
  { orgId: string; data: SsoConfiguration },
  TContext
> => {
  const mutationOptions = getInternalUpdateSsoConfigurationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get SSO configuration for the organization
 */
export const internalGetSsoConfiguration = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SsoConfiguration>(
    { url: `/internal/orgs/${orgId}/sso-configuration`, method: 'GET', signal },
    options,
  );
};

export const getInternalGetSsoConfigurationQueryKey = (orgId?: string) => {
  return [`/internal/orgs/${orgId}/sso-configuration`] as const;
};

export const getInternalGetSsoConfigurationQueryOptions = <
  TData = Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalGetSsoConfiguration>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInternalGetSsoConfigurationQueryKey(orgId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof internalGetSsoConfiguration>>> = ({
    signal,
  }) => internalGetSsoConfiguration(orgId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InternalGetSsoConfigurationQueryResult = NonNullable<
  Awaited<ReturnType<typeof internalGetSsoConfiguration>>
>;
export type InternalGetSsoConfigurationQueryError = ErrorType<N404NotFoundResponse>;

export function useInternalGetSsoConfiguration<
  TData = Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalGetSsoConfiguration>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
          TError,
          Awaited<ReturnType<typeof internalGetSsoConfiguration>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInternalGetSsoConfiguration<
  TData = Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalGetSsoConfiguration>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
          TError,
          Awaited<ReturnType<typeof internalGetSsoConfiguration>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInternalGetSsoConfiguration<
  TData = Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalGetSsoConfiguration>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get SSO configuration for the organization
 */

/**
 *
 */
export function useInternalGetSsoConfiguration<
  TData = Awaited<ReturnType<typeof internalGetSsoConfiguration>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof internalGetSsoConfiguration>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInternalGetSsoConfigurationQueryOptions(orgId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Log out the current session token
 */
export const logoutSession = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>({ url: `/auth/logout`, method: 'POST', signal }, options);
};

export const getLogoutSessionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof logoutSession>>, TError, void, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof logoutSession>>, TError, void, TContext> => {
  const mutationKey = ['logoutSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutSession>>, void> = () => {
    return logoutSession(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof logoutSession>>>;

export type LogoutSessionMutationError = ErrorType<unknown>;

/**
 * @summary Log out the current session token
 */
export const useLogoutSession = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logoutSession>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof logoutSession>>, TError, void, TContext> => {
  const mutationOptions = getLogoutSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Manually create an org membership
 */
export const internalCreateOrgMembership = (
  orgId: string,
  internalMembershipCreateBody: InternalMembershipCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OrgMembership>(
    {
      url: `/internal/orgs/${orgId}/memberships`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: internalMembershipCreateBody,
      signal,
    },
    options,
  );
};

export const getInternalCreateOrgMembershipMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalCreateOrgMembership>>,
    TError,
    { orgId: string; data: InternalMembershipCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalCreateOrgMembership>>,
  TError,
  { orgId: string; data: InternalMembershipCreateBody },
  TContext
> => {
  const mutationKey = ['internalCreateOrgMembership'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalCreateOrgMembership>>,
    { orgId: string; data: InternalMembershipCreateBody }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return internalCreateOrgMembership(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalCreateOrgMembershipMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalCreateOrgMembership>>
>;
export type InternalCreateOrgMembershipMutationBody = InternalMembershipCreateBody;
export type InternalCreateOrgMembershipMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Manually create an org membership
 */
export const useInternalCreateOrgMembership = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalCreateOrgMembership>>,
      TError,
      { orgId: string; data: InternalMembershipCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalCreateOrgMembership>>,
  TError,
  { orgId: string; data: InternalMembershipCreateBody },
  TContext
> => {
  const mutationOptions = getInternalCreateOrgMembershipMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Removes all user and service user access from an org.
 */
export const internalRemoveAccessFromOrg = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/internal/orgs/${orgId}/actions/remove-access`, method: 'POST', signal },
    options,
  );
};

export const getInternalRemoveAccessFromOrgMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>,
    TError,
    { orgId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationKey = ['internalRemoveAccessFromOrg'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>,
    { orgId: string }
  > = (props) => {
    const { orgId } = props ?? {};

    return internalRemoveAccessFromOrg(orgId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalRemoveAccessFromOrgMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>
>;

export type InternalRemoveAccessFromOrgMutationError = ErrorType<unknown>;

/**
 * @summary Removes all user and service user access from an org.
 */
export const useInternalRemoveAccessFromOrg = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>,
      TError,
      { orgId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalRemoveAccessFromOrg>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationOptions = getInternalRemoveAccessFromOrgMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Checks that the organization exists and stores the organization, project, and environment hierarchy used for inherited role bindings.
 *
 * @summary Sync authorization resources for all projects in an organization
 */
export const internalSyncOrgScopes = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScopeSyncResult>(
    { url: `/internal/orgs/${orgId}/actions/sync-scopes`, method: 'POST', signal },
    options,
  );
};

export const getInternalSyncOrgScopesMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalSyncOrgScopes>>,
    TError,
    { orgId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalSyncOrgScopes>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationKey = ['internalSyncOrgScopes'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalSyncOrgScopes>>,
    { orgId: string }
  > = (props) => {
    const { orgId } = props ?? {};

    return internalSyncOrgScopes(orgId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalSyncOrgScopesMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalSyncOrgScopes>>
>;

export type InternalSyncOrgScopesMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Sync authorization resources for all projects in an organization
 */
export const useInternalSyncOrgScopes = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalSyncOrgScopes>>,
      TError,
      { orgId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalSyncOrgScopes>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationOptions = getInternalSyncOrgScopesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Authenticate the current request and return From and Hash headers to the gateway
 */
export const internalAuthenticate = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>({ url: `/internal/authenticate`, method: 'POST', signal }, options);
};

export const getInternalAuthenticateMutationOptions = <
  TError = ErrorType<N401UnauthorizedResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalAuthenticate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalAuthenticate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['internalAuthenticate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalAuthenticate>>,
    void
  > = () => {
    return internalAuthenticate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalAuthenticateMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalAuthenticate>>
>;

export type InternalAuthenticateMutationError = ErrorType<N401UnauthorizedResponse>;

/**
 * @summary Authenticate the current request and return From and Hash headers to the gateway
 */
export const useInternalAuthenticate = <
  TError = ErrorType<N401UnauthorizedResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalAuthenticate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof internalAuthenticate>>, TError, void, TContext> => {
  const mutationOptions = getInternalAuthenticateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Perform a policy enforcement check on the requested user, subjects, and permissions
 */
export const internalAuthorize = (
  internalAuthorizeBody: InternalAuthorizeBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/internal/authorize`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: internalAuthorizeBody,
      signal,
    },
    options,
  );
};

export const getInternalAuthorizeMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalAuthorize>>,
    TError,
    { data: InternalAuthorizeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalAuthorize>>,
  TError,
  { data: InternalAuthorizeBody },
  TContext
> => {
  const mutationKey = ['internalAuthorize'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalAuthorize>>,
    { data: InternalAuthorizeBody }
  > = (props) => {
    const { data } = props ?? {};

    return internalAuthorize(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalAuthorizeMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalAuthorize>>
>;
export type InternalAuthorizeMutationBody = InternalAuthorizeBody;
export type InternalAuthorizeMutationError = ErrorType<
  N400BadRequestResponse | N403ForbiddenResponse
>;

/**
 * @summary Perform a policy enforcement check on the requested user, subjects, and permissions
 */
export const useInternalAuthorize = <
  TError = ErrorType<N400BadRequestResponse | N403ForbiddenResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalAuthorize>>,
      TError,
      { data: InternalAuthorizeBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalAuthorize>>,
  TError,
  { data: InternalAuthorizeBody },
  TContext
> => {
  const mutationOptions = getInternalAuthorizeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
