/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  InternalForceDeleteEnvironmentParams,
  InternalModuleCatalogue,
  InternalModuleCatalogueGenerateBody,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/controlplane';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * This is an escape hatch that may be used by privileged users to destroy an environment that cannot be fully destroyed or is facing errors that cannot be worked around.
This may leave infrastructure or state behind that must be cleaned up manually outside of the Orchestrator.
 
 * @summary Force delete the environment without a successful destroy deployment.
 */
export const internalForceDeleteEnvironment = (
  orgId: string,
  projectId: string,
  envId: string,
  params?: InternalForceDeleteEnvironmentParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/internal/orgs/${orgId}/projects/${projectId}/envs/${envId}/actions/force-delete`,
      method: 'POST',
      params,
      signal,
    },
    options,
  );
};

export const getInternalForceDeleteEnvironmentMutationOptions = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof internalForceDeleteEnvironment>>,
    TError,
    {
      orgId: string;
      projectId: string;
      envId: string;
      params?: InternalForceDeleteEnvironmentParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof internalForceDeleteEnvironment>>,
  TError,
  {
    orgId: string;
    projectId: string;
    envId: string;
    params?: InternalForceDeleteEnvironmentParams;
  },
  TContext
> => {
  const mutationKey = ['internalForceDeleteEnvironment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof internalForceDeleteEnvironment>>,
    {
      orgId: string;
      projectId: string;
      envId: string;
      params?: InternalForceDeleteEnvironmentParams;
    }
  > = (props) => {
    const { orgId, projectId, envId, params } = props ?? {};

    return internalForceDeleteEnvironment(orgId, projectId, envId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InternalForceDeleteEnvironmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof internalForceDeleteEnvironment>>
>;

export type InternalForceDeleteEnvironmentMutationError = ErrorType<
  N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary Force delete the environment without a successful destroy deployment.
 */
export const useInternalForceDeleteEnvironment = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof internalForceDeleteEnvironment>>,
      TError,
      {
        orgId: string;
        projectId: string;
        envId: string;
        params?: InternalForceDeleteEnvironmentParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof internalForceDeleteEnvironment>>,
  TError,
  {
    orgId: string;
    projectId: string;
    envId: string;
    params?: InternalForceDeleteEnvironmentParams;
  },
  TContext
> => {
  const mutationOptions = getInternalForceDeleteEnvironmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary An internal API to get all of the modules, rules, and providers that match an environment as well as any declared pinned versions.
 */
export const generateInternalModuleCatalogue = (
  orgId: string,
  projectId: string,
  envId: string,
  internalModuleCatalogueGenerateBody: InternalModuleCatalogueGenerateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InternalModuleCatalogue>(
    {
      url: `/internal/orgs/${orgId}/projects/${projectId}/envs/${envId}/module-catalogue`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: internalModuleCatalogueGenerateBody,
      signal,
    },
    options,
  );
};

export const getGenerateInternalModuleCatalogueMutationOptions = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateInternalModuleCatalogue>>,
    TError,
    { orgId: string; projectId: string; envId: string; data: InternalModuleCatalogueGenerateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateInternalModuleCatalogue>>,
  TError,
  { orgId: string; projectId: string; envId: string; data: InternalModuleCatalogueGenerateBody },
  TContext
> => {
  const mutationKey = ['generateInternalModuleCatalogue'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateInternalModuleCatalogue>>,
    { orgId: string; projectId: string; envId: string; data: InternalModuleCatalogueGenerateBody }
  > = (props) => {
    const { orgId, projectId, envId, data } = props ?? {};

    return generateInternalModuleCatalogue(orgId, projectId, envId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateInternalModuleCatalogueMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateInternalModuleCatalogue>>
>;
export type GenerateInternalModuleCatalogueMutationBody = InternalModuleCatalogueGenerateBody;
export type GenerateInternalModuleCatalogueMutationError = ErrorType<
  N404NotFoundResponse | N409ConflictResponse
>;

/**
 * @summary An internal API to get all of the modules, rules, and providers that match an environment as well as any declared pinned versions.
 */
export const useGenerateInternalModuleCatalogue = <
  TError = ErrorType<N404NotFoundResponse | N409ConflictResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateInternalModuleCatalogue>>,
      TError,
      {
        orgId: string;
        projectId: string;
        envId: string;
        data: InternalModuleCatalogueGenerateBody;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generateInternalModuleCatalogue>>,
  TError,
  { orgId: string; projectId: string; envId: string; data: InternalModuleCatalogueGenerateBody },
  TContext
> => {
  const mutationOptions = getGenerateInternalModuleCatalogueMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
