/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The schema for output parameters of the resource type
 */
export type AvailableResourceTypeOutputSchema = { [key: string]: unknown };
