/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { AvailableResourceTypeOption } from './availableResourceTypeOption';
import type { AvailableResourceTypeOutputSchema } from './availableResourceTypeOutputSchema';

/**
 * A page of available resource types returned from the list api.
 */
export interface AvailableResourceType {
  /** The unique identifier for the resource type */
  id: string;
  /**
   * Resource type description
   *
   * @maxLength 200
   */
  description?: string;
  /** The schema for output parameters of the resource type */
  output_schema: AvailableResourceTypeOutputSchema;
  /** A list of available options for the resource type */
  options: AvailableResourceTypeOption[];
}
