/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { AvailableResourceTypeOptionModuleParams } from './availableResourceTypeOptionModuleParams';

export interface AvailableResourceTypeOption {
  /** The unique identifier for the resource type */
  resource_id?: string;
  /** The class of the resource, which can be used to categorize it */
  resource_class: string;
  /** The unique identifier for the rule that this option belongs to */
  rule_id: string;
  /** The unique identifier for the module that this option belongs to */
  module_id: string;
  /** The parameters supported by the matched module. The orchestrator enforces that any required parameters are
provided and that they keys do not overlap with the 'module_inputs'.
   */
  module_params: AvailableResourceTypeOptionModuleParams;
}
