/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { CoreModuleVersionDetail } from './coreModuleVersionDetail';

export interface CoreModuleVersionPage {
  items: CoreModuleVersionDetail[];
  next_page_token?: string;
}
