/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A request to update an environment.
 */
export interface EnvironmentUpdateBody {
  /**
   * Environment human readable name. The id is used if this is not specified.
   *
   * @minLength 2
   * @maxLength 60
   * @pattern ^[^\p{Cc}\p{Cs}\p{Z}\n]( |[^\p{Cc}\p{Cs}\p{Z}\n])*[^\p{Cc}\p{Cs}\p{Z}\n]$
   */
  display_name: string;
}
