/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export interface EnvironmentModuleVersionPinCreateBody {
  project_uuid: string;
  environment_uuid: string;
  module_uuid: string;
  version_uuid: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  reason: string;
  confirm_defective_version_uuid?: string;
}
