/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A request to create a new environment.
 */
export interface EnvironmentCreateBody {
  /**
   * Environment identifier
   *
   * @pattern ^[a-z](?:-?[a-z0-9]+)+$
   */
  id: string;
  /**
   * The environment type for the new environment. This environment type must exist in the org.
   *
   * @pattern ^[a-z](?:-?[a-z0-9]+)+$
   */
  env_type_id: string;
  /**
   * Environment human readable name. The id is used if this is not specified.
   *
   * @minLength 2
   * @maxLength 60
   * @pattern ^[^\p{Cc}\p{Cs}\p{Z}\n]( |[^\p{Cc}\p{Cs}\p{Z}\n])*[^\p{Cc}\p{Cs}\p{Z}\n]$
   */
  display_name?: string;
}
