/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Summary of an environment type in the org.
 */
export interface EnvironmentTypeSummary {
  /** The unique id of the environment type in this org. */
  id: string;
  /** Unique uid for the environment type to identify a unique lifecycle */
  uuid: string;
  /** The date and time when the environment type was created */
  created_at: string;
  /** Human readable name for the environment type */
  display_name: string;
}
