/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A request to create a new environment type in the org.
 */
export interface EnvironmentTypeCreateBody {
  /**
   * Environment type identifier
   *
   * @pattern ^[a-z](?:-?[a-z0-9]+)+$
   */
  id: string;
  /**
   * Human readable name for the environment type. This will be generated if not provided.
   *
   * @maxLength 60
   */
  display_name?: string;
}
