/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Complete replacement label set used by module policy and add-on selectors.
 */
export type EnvironmentUpdateBodyLabels = { [key: string]: string };
