/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The request contents to generate a module catalogue
 */
export interface InternalModuleCatalogueGenerateBody {
  /** The normal response body only includes the latest versions for modules. However if there are pinned resources, we need to request the pinned versions as well which may no longer have rules associated with them. */
  pinned_module_versions?: string[];
  /** The normal response body only includes the modules and providers currently configured. However if we are removing nodes that still rely on providers we need to fetch their details without having the modules. */
  pinned_providers?: string[];
  /** When running a destroy deployment, we only care about pinned module version and do not need to check the rules. This option can be used to skip rule evaluation. */
  are_rules_ignored?: boolean;
}
