/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ResourceClass } from './resourceClass';
import type { ResourceId } from './resourceId';

/**
 * A rule within a module
 */
export interface InternalModuleCatalogueModuleRule {
  rule_id: string;
  resource_class: ResourceClass;
  resource_id?: ResourceId;
  /** The optional project id that this rule matches. */
  project_id?: string;
  /** The optional env type id that this rule matches. */
  env_type_id?: string;
  /** The optional environment id that this rule matches. */
  env_id?: string;
}
