/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The request contents to generate a module catalogue
 */
export interface InternalModuleCatalogueGenerateBody {
  /** The normal response body only includes the latest versions for modules. However if there are pinned resources, we need to request the pinned versions as well which may no longer have rules associated with them. */
  pinned_module_versions?: string[];
  /** The normal response body only includes the latest versions for modules. However if there are pinned resources, we need to request providers retained by the previous graph. */
  pinned_providers?: string[];
  /** When running a destroy deployment, only pinned module versions are required and rule evaluation is skipped. */
  are_rules_ignored?: boolean;
}
