/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { InternalRunnerAllOf } from './internalRunnerAllOf';
import type { Runner } from './runner';

/**
 * A summary of configuration a runner.
 */
export type InternalRunner = Runner & InternalRunnerAllOf;
