/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The source of the org state. This is used to identify the source of the org state, such as a git repository.
 */
export type InternalOrganizationAllOfSource =
  (typeof InternalOrganizationAllOfSource)[keyof typeof InternalOrganizationAllOfSource];

export const InternalOrganizationAllOfSource = {
  internal: 'internal',
  public: 'public',
} as const;
