/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { InternalModuleCatalogueModuleAllOfMigrationGeneration } from './internalModuleCatalogueModuleAllOfMigrationGeneration';
import type { InternalModuleCatalogueModuleRule } from './internalModuleCatalogueModuleRule';
import type { ModuleVerificationStatus } from './moduleVerificationStatus';
import type { ModuleVersionSemanticStatus } from './moduleVersionSemanticStatus';

export type InternalModuleCatalogueModuleAllOf = {
  rules: InternalModuleCatalogueModuleRule[];
  artifact_digest: string;
  semantic_status: ModuleVersionSemanticStatus;
  module_uuid: string;
  version_uuid: string;
  /** Canonical SemVer for managed versions; empty only for migrated v0 versions. */
  semantic_version: string;
  /** Authoritative persisted migration provenance. Only migrated v0 versions may reference external artifacts without a declared digest. */
  migration_generation: InternalModuleCatalogueModuleAllOfMigrationGeneration;
  verification_status: ModuleVerificationStatus;
};
