/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type InternalForceDeleteEnvironmentParams = {
  /**
   * Whether to delete all rules associated with the environment
   */
  deleteRules?: boolean;
};
