/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * Authoritative persisted migration provenance. Only migrated v0 versions may reference external artifacts without a declared digest.
 */
export type InternalModuleCatalogueModuleAllOfMigrationGeneration =
  (typeof InternalModuleCatalogueModuleAllOfMigrationGeneration)[keyof typeof InternalModuleCatalogueModuleAllOfMigrationGeneration];

export const InternalModuleCatalogueModuleAllOfMigrationGeneration = {
  v0: 'v0',
  v1: 'v1',
  managed: 'managed',
} as const;
