/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A request to create a new organization state in the control plane.
 */
export interface InternalOrganizationCreateBody {
  /**
   * The unique identifier of the org. It will be auto-generated if not provided.
   *
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-z](?:-?[a-z0-9]+)+$
   */
  id?: string;
  /**
   * An id prefix for the org. If will be a prefix to the auto-generated id.
   *
   * @minLength 1
   * @maxLength 15
   * @pattern ^[a-z](?:-?[a-z0-9]+)+$
   */
  id_prefix?: string;
}
