/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ConfigurationSecret } from './configurationSecret';

export type InternalRunnerAllOf = {
  runner_configuration_secret?: ConfigurationSecret;
};
