/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type K8sAgentRunnerConfigurationType =
  (typeof K8sAgentRunnerConfigurationType)[keyof typeof K8sAgentRunnerConfigurationType];

export const K8sAgentRunnerConfigurationType = {
  'kubernetes-agent': 'kubernetes-agent',
} as const;
