/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type K8sEksRunnerConfigurationUpdateBodyType =
  (typeof K8sEksRunnerConfigurationUpdateBodyType)[keyof typeof K8sEksRunnerConfigurationUpdateBodyType];

export const K8sEksRunnerConfigurationUpdateBodyType = {
  'kubernetes-eks': 'kubernetes-eks',
} as const;
