/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { K8sEksRunnerConfigurationType } from './k8sEksRunnerConfigurationType';
import type { K8sRunnerEksCluster } from './k8sRunnerEksCluster';
import type { K8sRunnerJobConfig } from './k8sRunnerJobConfig';

/**
 * Runner configuration for an EKS cluster.
 */
export interface K8sEksRunnerConfiguration {
  type: K8sEksRunnerConfigurationType;
  job: K8sRunnerJobConfig;
  cluster: K8sRunnerEksCluster;
}
