/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { K8sRunnerConfigurationUpdateBodyType } from './k8sRunnerConfigurationUpdateBodyType';
import type { K8sRunnerJobConfig } from './k8sRunnerJobConfig';
import type { K8sRunnerK8sCluster } from './k8sRunnerK8sCluster';

/**
 * Object to update an existing runner configuration for a Kubernetes cluster.
 */
export interface K8sRunnerConfigurationUpdateBody {
  job?: K8sRunnerJobConfig;
  cluster?: K8sRunnerK8sCluster;
  type: K8sRunnerConfigurationUpdateBodyType;
}
