/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { K8sRunnerJobConfigPodTemplate } from './k8sRunnerJobConfigPodTemplate';

/**
 * Properties of the Kubernetes Runner Job.
 */
export interface K8sRunnerJobConfig {
  /** Namespace where the Job runs. */
  namespace: string;
  /** Service Account the Job runs with. */
  service_account: string;
  /** The Pod Template Spec manifest which defines the runner job pod in the target cluster. It will be merged with the default Job Pod Template Spec.
   */
  pod_template?: K8sRunnerJobConfigPodTemplate;
}
