/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type ListEnvironmentModuleVersionPinsParams = {
  environment_uuid?: string;
  module_uuid?: string;
  include_removed?: boolean;
};
