/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { PageTokenQueryParamParameter } from './pageTokenQueryParamParameter';
import type { PerPageQueryParamParameter } from './perPageQueryParamParameter';

export type ListEnvironmentsParams = {
  /**
   * The maximum number of items to return in a page of results
   */
  per_page?: PerPageQueryParamParameter;
  /**
   * The page token to request from
   */
  page?: PageTokenQueryParamParameter;
  /**
   * Filter the list by environment types
   */
  byEnvTypeId?: string[];
};
