/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { IncludeNonDeveloperAccessibleQueryParamParameter } from './includeNonDeveloperAccessibleQueryParamParameter';
import type { PageTokenQueryParamParameter } from './pageTokenQueryParamParameter';
import type { PerPageQueryParamParameter } from './perPageQueryParamParameter';
import type { ResourceTypeIdQueryParamParameter } from './resourceTypeIdQueryParamParameter';

export type ListAvailableResourceTypesParams = {
  /**
   * The maximum number of items to return in a page of results
   */
  per_page?: PerPageQueryParamParameter;
  /**
   * The page token to request from
   */
  page?: PageTokenQueryParamParameter;
  /**
   * Filter by resource type id.
   */
  type_id?: ResourceTypeIdQueryParamParameter;
  /**
   * If true, the list will include resources that are not accessible to developers.
   */
  include_non_developer_accessible?: IncludeNonDeveloperAccessibleQueryParamParameter;
};
