/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifest } from './moduleCoProvisionManifest';
import type { ModuleOutputSchema } from './moduleOutputSchema';
import type { ModuleVersionComparisonSnapshotDependencies } from './moduleVersionComparisonSnapshotDependencies';
import type { ModuleVersionComparisonSnapshotModuleInputs } from './moduleVersionComparisonSnapshotModuleInputs';
import type { ModuleVersionComparisonSnapshotModuleParams } from './moduleVersionComparisonSnapshotModuleParams';
import type { ModuleVersionComparisonSnapshotProviderMapping } from './moduleVersionComparisonSnapshotProviderMapping';

export interface ModuleVersionComparisonSnapshot {
  output_schema?: ModuleOutputSchema;
  module_source: string;
  /** @nullable */
  module_source_code: string | null;
  artifact_digest: string;
  source_revision: string;
  resource_type: string;
  module_inputs: ModuleVersionComparisonSnapshotModuleInputs;
  module_params: ModuleVersionComparisonSnapshotModuleParams;
  provider_mapping: ModuleVersionComparisonSnapshotProviderMapping;
  dependencies: ModuleVersionComparisonSnapshotDependencies;
  coprovisioned: ModuleCoProvisionManifest[];
}
