/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCatalogueCreateBodyTags } from './moduleCatalogueCreateBodyTags';
import type { ModuleId } from './moduleId';

export interface ModuleCatalogueCreateBody {
  slug: ModuleId;
  /**
   * @minLength 1
   * @maxLength 200
   */
  display_name?: string;
  /** @maxLength 2000 */
  description?: string;
  /**
   * @minLength 2
   * @maxLength 200
   */
  resource_type: string;
  tags?: ModuleCatalogueCreateBodyTags;
}
