/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleExtensionContributionKind } from './moduleExtensionContributionKind';
import type { ModuleExtensionContributionLifecycleState } from './moduleExtensionContributionLifecycleState';
import type { ModuleExtensionContributionPayload } from './moduleExtensionContributionPayload';

export interface ModuleExtensionContribution {
  id: string;
  module_uuid: string;
  version_uuid?: string;
  environment_uuid?: string;
  /** @pattern ^[a-z][a-z0-9.-]*$ */
  namespace: string;
  external_resource_id: string;
  kind: ModuleExtensionContributionKind;
  lifecycle_state: ModuleExtensionContributionLifecycleState;
  label: string;
  target_url?: string;
  payload: ModuleExtensionContributionPayload;
  created_by: string;
  created_at: string;
  updated_at: string;
}
