/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 */

/**
 * The fixed inputs to this module. These may contain expressions referencing the modules context.
 */
export type ModuleAllOfModuleInputs = { [key: string]: unknown };
