/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleSummaryAllOf } from './moduleSummaryAllOf';
import type { ModuleVersionSummaryCoreFields } from './moduleVersionSummaryCoreFields';

/**
 * A summary of the module that maps an OpenTofu module to a resource type. The full details can be retrieved through the Get api.
 */
export type ModuleSummary = ModuleVersionSummaryCoreFields & ModuleSummaryAllOf;
