/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleExtensionContributionUpsertBodyKind } from './moduleExtensionContributionUpsertBodyKind';
import type { ModuleExtensionContributionUpsertBodyLifecycleState } from './moduleExtensionContributionUpsertBodyLifecycleState';
import type { ModuleExtensionContributionUpsertBodyPayload } from './moduleExtensionContributionUpsertBodyPayload';

export interface ModuleExtensionContributionUpsertBody {
  version_uuid?: string;
  environment_uuid?: string;
  /** @pattern ^[a-z][a-z0-9.-]*$ */
  namespace: string;
  /** @minLength 1 */
  external_resource_id: string;
  kind: ModuleExtensionContributionUpsertBodyKind;
  lifecycle_state: ModuleExtensionContributionUpsertBodyLifecycleState;
  /** @minLength 1 */
  label: string;
  target_url?: string;
  payload: ModuleExtensionContributionUpsertBodyPayload;
}
