/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleDependencyManifest } from './moduleDependencyManifest';

/**
 * A mapping of alias to resource dependencies that must be provisioned with this module
 */
export type ModuleCoreFieldsDependencies = { [key: string]: ModuleDependencyManifest };
