/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type ModuleCatalogueStatus =
  (typeof ModuleCatalogueStatus)[keyof typeof ModuleCatalogueStatus];

export const ModuleCatalogueStatus = {
  ModuleCatalogueStatusActive: 'active',
  ModuleCatalogueStatusArchived: 'archived',
} as const;
