/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoreFields } from './moduleCoreFields';
import type { ModuleVersionSummary } from './moduleVersionSummary';

/**
 * Configuration for an OpenTofu provider that will be used in modules
 */
export type ModuleVersion = ModuleVersionSummary & ModuleCoreFields;
