/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { EnvironmentModuleVersionPin } from './environmentModuleVersionPin';
import type { ModuleVersionPinBulkAction } from './moduleVersionPinBulkAction';

export interface ModuleVersionPinBulkResult {
  operation_id: string;
  action: ModuleVersionPinBulkAction;
  pins: EnvironmentModuleVersionPin[];
}
