/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionPinBulkAction } from './moduleVersionPinBulkAction';

export interface ModuleVersionPinBulkPreviewBody {
  action: ModuleVersionPinBulkAction;
  module_uuid: string;
  /**
   * @minItems 1
   * @maxItems 500
   */
  environment_uuids: string[];
  confirm_defective_version_uuids?: string[];
}
