/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifest } from './moduleCoProvisionManifest';
import type { ModuleCoreFieldsDependencies } from './moduleCoreFieldsDependencies';
import type { ModuleCoreFieldsModuleInputs } from './moduleCoreFieldsModuleInputs';
import type { ModuleCoreFieldsModuleParams } from './moduleCoreFieldsModuleParams';

export interface ModuleCoreFields {
  /** The parameters supported by this module. The orchestrator enforces that any required parameters are
provided and that they keys do not overlap with the 'module_inputs'.
   */
  module_params: ModuleCoreFieldsModuleParams;
  /** The fixed inputs to this module. These may contain expressions referencing the modules context. */
  module_inputs: ModuleCoreFieldsModuleInputs;
  /** The source code of the OpenTofu module backing this module if the module_source is 'inline'. */
  module_source_code?: string;
  /** A mapping of alias to resource dependencies that must be provisioned with this module */
  dependencies: ModuleCoreFieldsDependencies;
  /** A set of resources to provision after or in parallel with the resource of the current module. */
  coprovisioned: ModuleCoProvisionManifest[];
}
