/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifestParams } from './moduleCoProvisionManifestParams';
import type { ResourceClass } from './resourceClass';
import type { ResourceId } from './resourceId';

/**
 * A resource to provision after or in parallel with the resource of the current module.
 */
export interface ModuleCoProvisionManifest {
  /**
   * The resource type to provision
   *
   * @minLength 2
   * @maxLength 63
   * @pattern ^[A-Za-z0-9][A-Za-z0-9-]{0,61}[A-Za-z0-9]$
   */
  type: string;
  class?: ResourceClass;
  id?: ResourceId;
  /**
   * The parameters to pass for provisioning.
   *
   * @maxItems 20
   */
  params?: ModuleCoProvisionManifestParams;
  /** If true, this coprovisioned resource will have a dependency on the current resource so that the current
resource must be successfully provisioned before the coprovisioned one is.
   */
  is_dependent_on_current?: boolean;
  /** If true, all resources that depend on the current resource will also depend on (be provisioned after) this coprovisioned resource.
   */
  copy_dependents_from_current?: boolean;
}
