/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifest } from './moduleCoProvisionManifest';
import type { ModuleVersionPublishBodyDependencies } from './moduleVersionPublishBodyDependencies';
import type { ModuleVersionPublishBodyModuleInputs } from './moduleVersionPublishBodyModuleInputs';
import type { ModuleVersionPublishBodyModuleParams } from './moduleVersionPublishBodyModuleParams';
import type { ModuleVersionPublishBodyProviderMapping } from './moduleVersionPublishBodyProviderMapping';

export interface ModuleVersionPublishBody {
  /** @pattern ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$ */
  semantic_version: string;
  /** @pattern ^sha256:[a-f0-9]{64}$ */
  artifact_digest?: string;
  /** @maxLength 500 */
  source_revision?: string;
  /** @maxLength 10000 */
  release_notes?: string;
  /** @maxLength 2000 */
  description?: string;
  /**
   * @minLength 2
   * @maxLength 200
   */
  module_source: string;
  module_source_code?: string;
  module_params: ModuleVersionPublishBodyModuleParams;
  module_inputs: ModuleVersionPublishBodyModuleInputs;
  provider_mapping: ModuleVersionPublishBodyProviderMapping;
  dependencies: ModuleVersionPublishBodyDependencies;
  /** @maxItems 20 */
  coprovisioned: ModuleCoProvisionManifest[];
}
