/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export interface ModuleVersionPinBulkPreviewItem {
  environment_uuid: string;
  project_uuid: string;
  environment_id: string;
  project_id: string;
  environment_type?: string;
  production: boolean;
  eligible: boolean;
  version_uuid?: string;
  pin_id?: string;
  pin_resource_version?: number;
  idempotent_match?: boolean;
  problem?: string;
}
