/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionLifecycleTransactionItem } from './moduleVersionLifecycleTransactionItem';

export interface ModuleVersionLifecycleTransactionBody {
  /**
   * @minItems 1
   * @maxItems 100
   */
  transitions: ModuleVersionLifecycleTransactionItem[];
}
