/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleProviderCreateBodyConfiguration } from './moduleProviderCreateBodyConfiguration';

/**
 * A request to create a new module provider.
 */
export interface ModuleProviderCreateBody {
  /**
   * The OpenTofu provider name
   *
   * @maxLength 100
   * @pattern ^[a-z][a-z0-9_-]+$
   */
  provider_type: string;
  /**
   * The unique identifier for this module provider under the given provider type
   *
   * @maxLength 100
   * @pattern ^[a-z][a-z0-9_-]+$
   */
  id: string;
  /**
   * An optional text description for this module provider
   *
   * @maxLength 200
   */
  description?: string;
  /**
   * The OpenTofu provider source as a registry coordinate
   *
   * @maxLength 100
   * @pattern ^([a-z0-9.-]+/)?([a-z][a-z0-9_-]+)/([a-z][a-z0-9_-]+)$
   */
  source: string;
  /**
   * Specify a specific version of the provider
   *
   * @maxLength 100
   * @pattern ^((=|!=|>|>=|<|<=|~>) ([0-9.]+(-.+)?))(, (=|!=|>|>=|<|<=|~>) ([0-9.]+(-.+)?))*$
   */
  version_constraint: string;
  /**
   * Any required configuration for this provider when used.
   *
   * @maxItems 20
   */
  configuration?: ModuleProviderCreateBodyConfiguration;
}
