/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The fixed inputs to this module. These may contain expressions referencing the modules context.
 *
 * @maxItems 20
 */
export type ModuleCreateBodyModuleInputs = { [key: string]: unknown };
