/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionPinOverrideReconcileBodyOutcome } from './moduleVersionPinOverrideReconcileBodyOutcome';

export interface ModuleVersionPinOverrideReconcileBody {
  /** @minimum 1 */
  expected_resource_version: number;
  operation_id: string;
  outcome: ModuleVersionPinOverrideReconcileBodyOutcome;
  deployment_id: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  reason: string;
}
