/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionPinBulkAction } from './moduleVersionPinBulkAction';

export interface ModuleVersionPinBulkCommandBody {
  action: ModuleVersionPinBulkAction;
  module_uuid: string;
  /**
   * @minItems 1
   * @maxItems 500
   */
  environment_uuids: string[];
  /**
   * @minLength 64
   * @maxLength 64
   */
  preview_fingerprint: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  reason: string;
  confirm_defective_version_uuids?: string[];
}
