/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifest } from './moduleCoProvisionManifest';
import type { ModuleCreateBodyDependencies } from './moduleCreateBodyDependencies';
import type { ModuleCreateBodyModuleInputs } from './moduleCreateBodyModuleInputs';
import type { ModuleCreateBodyModuleParams } from './moduleCreateBodyModuleParams';
import type { ModuleCreateBodyProviderMapping } from './moduleCreateBodyProviderMapping';
import type { ModuleId } from './moduleId';

/**
 * A request to create a new module
 */
export interface ModuleCreateBody {
  id: ModuleId;
  /**
   * An optional text description for this module
   *
   * @maxLength 200
   */
  description?: string;
  /**
   * The resource type that this module provisions.
   *
   * @minLength 2
   */
  resource_type: string;
  /**
   * The source of the OpenTofu module backing this module.
   *
   * @minLength 2
   * @maxLength 200
   */
  module_source: string;
  /** The source code of the OpenTofu module backing this module. Required, if module_source is 'inline'. */
  module_source_code?: string;
  /** The parameters supported by this module. The orchestrator enforces that any required parameters are
provided and that they keys do not overlap with the 'module_inputs'.
   */
  module_params?: ModuleCreateBodyModuleParams;
  /**
   * The fixed inputs to this module. These may contain expressions referencing the modules context.
   *
   * @maxItems 20
   */
  module_inputs?: ModuleCreateBodyModuleInputs;
  /**
   * A mapping of module providers to use when provisioning using this module.
   *
   * @maxItems 20
   */
  provider_mapping?: ModuleCreateBodyProviderMapping;
  /**
   * A mapping of alias to resource dependencies that must be provisioned with this module
   *
   * @maxItems 20
   */
  dependencies?: ModuleCreateBodyDependencies;
  /**
   * A set of resources to provision after or in parallel with the resource of the current module.
   *
   * @maxItems 20
   */
  coprovisioned?: ModuleCoProvisionManifest[];
}
