/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleSummary } from './moduleSummary';

/**
 * A page of the list modules response.
 */
export interface ModulePage {
  /** The items in this page */
  items: ModuleSummary[];
  /** The page token to use to request the next page of items */
  next_page_token?: string;
}
