/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionUsageByEnvironmentType } from './moduleVersionUsageByEnvironmentType';
import type { ModuleVersionUsageByProject } from './moduleVersionUsageByProject';
import type { ModuleVersionUsageEnvironment } from './moduleVersionUsageEnvironment';

export interface ModuleVersionUsage {
  module_uuid: string;
  version_uuid: string;
  semantic_version: string;
  /** @minimum 0 */
  active_environment_count: number;
  by_project: ModuleVersionUsageByProject;
  by_environment_type: ModuleVersionUsageByEnvironmentType;
  environments: ModuleVersionUsageEnvironment[];
  unknown_environments: string[];
  observed_at: string;
  /** @minimum 0 */
  active_pins: number;
  /** @minimum 0 */
  override_pending_pins: number;
  /** @minimum 0 */
  historical_pins: number;
}
