/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The type of input supported for this parameter. This will be enforced by the orchestrator at graph creation
time when values are known ahead of time. Use 'any' to indicate no type constraint.
 
 */
export type ModuleParamItemType = (typeof ModuleParamItemType)[keyof typeof ModuleParamItemType];

export const ModuleParamItemType = {
  string: 'string',
  number: 'number',
  bool: 'bool',
  list: 'list',
  map: 'map',
  any: 'any',
} as const;
