/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleVersionComparisonSnapshot } from './moduleVersionComparisonSnapshot';

export interface ModuleVersionComparison {
  from_version_uuid: string;
  to_version_uuid: string;
  before: ModuleVersionComparisonSnapshot;
  after: ModuleVersionComparisonSnapshot;
  module_source_changed: boolean;
  module_source_code_changed: boolean;
  artifact_digest_changed: boolean;
  source_revision_changed: boolean;
  resource_type_changed: boolean;
  added_module_inputs: string[];
  removed_module_inputs: string[];
  changed_module_inputs: string[];
  added_module_params: string[];
  removed_module_params: string[];
  changed_module_params: string[];
  added_provider_mappings: string[];
  removed_provider_mappings: string[];
  changed_provider_mappings: string[];
  added_dependencies: string[];
  removed_dependencies: string[];
  changed_dependencies: string[];
  coprovisioning_changed: boolean;
  output_schema_changed: boolean;
}
