/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleDependencyManifest } from './moduleDependencyManifest';

export type ModuleVersionPublishBodyDependencies = { [key: string]: ModuleDependencyManifest };
