/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * A mapping of module providers to use when provisioning using this module
 */
export type ModuleVersionSummaryCoreFieldsProviderMapping = { [key: string]: string };
