/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleParamItemType } from './moduleParamItemType';

/**
 * The definition of a parameter that can be provided when using this module.
 */
export interface ModuleParamItem {
  /** The type of input supported for this parameter. This will be enforced by the orchestrator at graph creation
time when values are known ahead of time. Use 'any' to indicate no type constraint.
   */
  type: ModuleParamItemType;
  /** Whether this parameter is optional. Defaults to false. */
  is_optional?: boolean;
  /** An optional description that helps a user define the correct value. */
  description?: string;
}
