/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ModuleCoProvisionManifest } from './moduleCoProvisionManifest';
import type { ModuleUpdateBodyDependencies } from './moduleUpdateBodyDependencies';
import type { ModuleUpdateBodyModuleInputs } from './moduleUpdateBodyModuleInputs';
import type { ModuleUpdateBodyModuleParams } from './moduleUpdateBodyModuleParams';
import type { ModuleUpdateBodyProviderMapping } from './moduleUpdateBodyProviderMapping';

/**
 * A request to update an existing module
 */
export interface ModuleUpdateBody {
  /**
   * An optional text description for this module
   *
   * @maxLength 200
   */
  description?: string;
  /**
   * The source of the OpenTofu module backing this module.
   *
   * @minLength 2
   * @maxLength 200
   */
  module_source?: string;
  /** The source code of the OpenTofu module backing this module. */
  module_source_code?: string;
  /** The parameters supported by this module. The orchestrator enforces that any required parameters are
provided and that they keys do not overlap with the 'module_inputs'.
   */
  module_params?: ModuleUpdateBodyModuleParams;
  /**
   * The inputs to the module. These may contain expressions referencing the modules context.
   *
   * @maxItems 20
   */
  module_inputs?: ModuleUpdateBodyModuleInputs;
  /**
   * A mapping of module providers to use when provisioning using this module.
   *
   * @maxItems 20
   */
  provider_mapping?: ModuleUpdateBodyProviderMapping;
  /**
   * A mapping of alias to resource dependencies that must be provisioned with this module
   *
   * @maxItems 20
   */
  dependencies?: ModuleUpdateBodyDependencies;
  /**
   * A set of resources to provision after or in parallel with the resource of the current module.
   *
   * @maxItems 20
   */
  coprovisioned?: ModuleCoProvisionManifest[];
}
