/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type ModuleVersionLifecycleTransactionItemAction =
  (typeof ModuleVersionLifecycleTransactionItemAction)[keyof typeof ModuleVersionLifecycleTransactionItemAction];

export const ModuleVersionLifecycleTransactionItemAction = {
  promote: 'promote',
  deprecate: 'deprecate',
  'mark-defective': 'mark-defective',
  restore: 'restore',
} as const;
