/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The parameters to pass for provisioning.
 *
 * @maxItems 20
 */
export type ModuleCoProvisionManifestParams = { [key: string]: unknown };
