/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { Error } from './error';

/**
 * The request conflicts with existing state in the system.
 */
export type N409ConflictResponse = Error;
