/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The current status of the org.
 */
export type OrganizationStatus = (typeof OrganizationStatus)[keyof typeof OrganizationStatus];

export const OrganizationStatus = {
  active: 'active',
  deleting: 'deleting',
  delete_failed: 'delete_failed',
  deleted: 'deleted',
} as const;
