/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 */
import type { Organization } from './organization';

/**
 * A page of organization state returned from the list api.
 */
export interface OrganizationPage {
  /** The items in this page */
  items: Organization[];
  /** The page token to use to request the next page of items */
  next_page_token?: string;
}
