/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ResourceTypeUpdateBodyOutputSchema } from './resourceTypeUpdateBodyOutputSchema';

/**
 * A request to update a resource type.
 */
export interface ResourceTypeUpdateBody {
  /**
   * Resource type description
   *
   * @maxLength 200
   */
  description?: string;
  /** Schema for output parameters */
  output_schema?: ResourceTypeUpdateBodyOutputSchema;
  /** Indicates if this resource type is for developers to use in the manifest. Resource types with this flag set to false, will not be available as types of resources in a manifest. */
  is_developer_accessible?: boolean;
}
