/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { ResourceTypeCatalogueStatus } from './resourceTypeCatalogueStatus';
import type { ResourceTypeModuleContract } from './resourceTypeModuleContract';
import type { ResourceTypeOutputSchema } from './resourceTypeOutputSchema';

/**
 * A resource type that can be used in modules.
 */
export interface ResourceType {
  /** Resource type identifier */
  id: string;
  /**
   * Resource type description
   *
   * @maxLength 200
   */
  description?: string;
  /** Schema for output parameters */
  output_schema: ResourceTypeOutputSchema;
  module_contract?: ResourceTypeModuleContract;
  /** The date and time when the resource type was created */
  created_at: string;
  /** Indicates if this is a built-in resource type */
  built_in: boolean;
  /** Indicates if this resource type is for developers to use in the manifest. Resource types with this flag set to false will not be available as types of resources in a manifest. */
  is_developer_accessible: boolean;
  catalogue_status: ResourceTypeCatalogueStatus;
  /** @minimum 1 */
  resource_version: number;
  archived_at?: string;
  archived_by?: string;
  archive_reason?: string;
}
