/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { RunnerType } from './runnerType';

/**
 * A summary of the runner configuration.
 */
export interface RunnerConfigurationSummary {
  type: RunnerType;
}
