/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

/**
 * The properties required to create a new rule that matches runners
 */
export interface RunnerRuleCreateBody {
  /** The unique identifier for a runner */
  runner_id: string;
  /** The environment type to match this rule. This environment type must exist in the org.
   */
  env_type_id?: string;
  /** Project identifier to match this rule. This project must exist in the org.
   */
  project_id?: string;
}
