/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { RunnerConfigurationUpdate } from './runnerConfigurationUpdate';
import type { StateStorageConfiguration } from './stateStorageConfiguration';

/**
 * A request to update a runner
 */
export interface RunnerUpdateBody {
  /** An optional text description for this runner. */
  description?: string;
  runner_configuration?: RunnerConfigurationUpdate;
  state_storage_configuration?: StateStorageConfiguration;
}
