/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { RunnerRuleSummary } from './runnerRuleSummary';

/**
 * A page of rules returned from the list api.
 */
export interface RunnerRulePage {
  /** The items in this page. */
  items: RunnerRuleSummary[];
  /** The page token to use to request the next page of items. */
  next_page_token?: string;
}
