/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { S3StorageConfigurationType } from './s3StorageConfigurationType';

/**
 * Configuration to use an AWS S3 bucket as state storage backend of this runner. Authentication and other settings
can be set via environment variables and defaults. See <https://developer.hashicorp.com/terraform/language/backend/s3#state-storage>
for more details.
 */
export interface S3StorageConfiguration {
  type: S3StorageConfigurationType;
  /**
   * Name of the S3 Bucket.
   *
   * @pattern ^[a-z0-9][a-z0-9\-]*[a-z0-9]$
   */
  bucket: string;
  /**
   * A prefix path for the state file. The environment uuid will be used as a unique key within this.
   *
   * @pattern ^[a-zA-Z0-9._-]+(?:\/[a-zA-Z0-9._-]+)*\/?$
   */
  path_prefix?: string;
}
