/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { SandboxAllOfInputs } from './sandboxAllOfInputs';

export type SandboxAllOf = {
  /** The status of the sandbox. */
  status: string;
  /** The inputs to the sandbox. */
  inputs: SandboxAllOfInputs;
  /** The service user token created for the sandbox. */
  token: string;
  /** The date and time when the sandbox was created. */
  created_at: string;
  /** The date and time when the sandbox deployment completed. */
  completed_at?: string;
};
