/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { SandboxAllOf } from './sandboxAllOf';
import type { SandboxSummary } from './sandboxSummary';

/**
 * The full details of a sandbox
 */
export type Sandbox = SandboxSummary & SandboxAllOf;
