/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */

export type ServerlessEcsRunnerConfigurationType =
  (typeof ServerlessEcsRunnerConfigurationType)[keyof typeof ServerlessEcsRunnerConfigurationType];

export const ServerlessEcsRunnerConfigurationType = {
  'serverless-ecs': 'serverless-ecs',
} as const;
