/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { AwsTemporaryAuth } from './awsTemporaryAuth';
import type { ServerlessEcsRunnerConfigurationType } from './serverlessEcsRunnerConfigurationType';
import type { ServerlessEcsRunnerJob } from './serverlessEcsRunnerJob';

/**
 * Runner configuration for executing on AWS ECS Fargate.
 */
export interface ServerlessEcsRunnerConfiguration {
  type: ServerlessEcsRunnerConfigurationType;
  auth: AwsTemporaryAuth;
  job: ServerlessEcsRunnerJob;
}
