/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { CoreModuleVersion } from './coreModuleVersion';

export interface StableModuleVersionSuccessorResult {
  prerelease: CoreModuleVersion;
  stable: CoreModuleVersion;
  correlation_id: string;
}
