/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { StateStorageType } from './stateStorageType';

/**
 * Summary of the state storage configuration.
 */
export interface StateStorageConfigurationSummary {
  type: StateStorageType;
}
