/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { AzureRMStorageConfiguration } from './azureRMStorageConfiguration';
import type { GCSStorageConfiguration } from './gCSStorageConfiguration';
import type { K8sStorageConfiguration } from './k8sStorageConfiguration';
import type { S3StorageConfiguration } from './s3StorageConfiguration';

/**
 * Configuration for the Terraform Backend used by the runner.
 */
export type StateStorageConfiguration =
  | K8sStorageConfiguration
  | S3StorageConfiguration
  | GCSStorageConfiguration
  | AzureRMStorageConfiguration;
