/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type { DryRunQueryParamParameter } from './dryRunQueryParamParameter';

export type UpdateRunnerInAnEnvironmentParams = {
  /**
   * If true, the request will not make any changes to the system, but will return what would have been done.
   */
  dry_run?: DryRunQueryParamParameter;
};
