/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  AcceptedDeviceLoginRequest,
  CreatedDeviceLoginRequest,
  DeviceLoginRequest,
  N400BadRequestResponse,
  N404NotFoundResponse,
} from '../../../../../models/v2/iam';

export const getRequestDeviceLoginResponseMock = (): CreatedDeviceLoginRequest => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    polling_token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    approval_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
});

export const getRequestDeviceLoginResponseMock201 = (): CreatedDeviceLoginRequest => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    polling_token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    approval_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    code: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
});

export const getRequestDeviceLoginResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getPollDeviceLoginRequestResponseMock = (): AcceptedDeviceLoginRequest | void => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    token_expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
});

export const getPollDeviceLoginRequestResponseMock200 = (): AcceptedDeviceLoginRequest => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    token_expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
});

export const getPollDeviceLoginRequestResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getPollDeviceLoginRequestResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetDeviceLoginRequestResponseMock = (): DeviceLoginRequest => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    user_agent: faker.string.alpha({ length: { min: 10, max: 20 } }),
    client_ip: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    client_city: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    client_region: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  },
});

export const getGetDeviceLoginRequestResponseMock200 = (): DeviceLoginRequest => ({
  ...{
    id: faker.string.uuid(),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
    expires_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    user_agent: faker.string.alpha({ length: { min: 10, max: 20 } }),
    client_ip: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    client_city: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    client_region: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  },
});

export const getGetDeviceLoginRequestResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getAcceptDeviceLoginRequestResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getRejectDeviceLoginRequestResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getRequestDeviceLoginMockHandler = (
  overrideResponse?:
    | CreatedDeviceLoginRequest
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreatedDeviceLoginRequest> | CreatedDeviceLoginRequest),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/auth/device',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRequestDeviceLoginResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getRequestDeviceLoginMockHandler201 = (
  overrideResponse?:
    | CreatedDeviceLoginRequest
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreatedDeviceLoginRequest> | CreatedDeviceLoginRequest),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/auth/device',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRequestDeviceLoginResponseMock201(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getRequestDeviceLoginMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/auth/device',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRequestDeviceLoginResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getPollDeviceLoginRequestMockHandler = (
  overrideResponse?:
    | AcceptedDeviceLoginRequest
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<AcceptedDeviceLoginRequest | void> | AcceptedDeviceLoginRequest | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/poll',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPollDeviceLoginRequestResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getPollDeviceLoginRequestMockHandler200 = (
  overrideResponse?:
    | AcceptedDeviceLoginRequest
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<AcceptedDeviceLoginRequest> | AcceptedDeviceLoginRequest),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/poll',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPollDeviceLoginRequestResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getPollDeviceLoginRequestMockHandler202 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/poll',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 202 });
    },
    options,
  );
};

export const getPollDeviceLoginRequestMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/poll',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPollDeviceLoginRequestResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getPollDeviceLoginRequestMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/poll',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getPollDeviceLoginRequestResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetDeviceLoginRequestMockHandler = (
  overrideResponse?:
    | DeviceLoginRequest
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<DeviceLoginRequest> | DeviceLoginRequest),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/devicelogins/:code',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetDeviceLoginRequestResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetDeviceLoginRequestMockHandler200 = (
  overrideResponse?:
    | DeviceLoginRequest
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<DeviceLoginRequest> | DeviceLoginRequest),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/devicelogins/:code',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetDeviceLoginRequestResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetDeviceLoginRequestMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/devicelogins/:code',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetDeviceLoginRequestResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getAcceptDeviceLoginRequestMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/accept',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getAcceptDeviceLoginRequestMockHandler204 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/accept',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getAcceptDeviceLoginRequestMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/accept',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getAcceptDeviceLoginRequestResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getRejectDeviceLoginRequestMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/reject',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getRejectDeviceLoginRequestMockHandler204 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/reject',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getRejectDeviceLoginRequestMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/devicelogins/:requestId/actions/reject',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getRejectDeviceLoginRequestResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getDeviceMock = () => [
  getRequestDeviceLoginMockHandler(),
  getPollDeviceLoginRequestMockHandler(),
  getGetDeviceLoginRequestMockHandler(),
  getAcceptDeviceLoginRequestMockHandler(),
  getRejectDeviceLoginRequestMockHandler(),
];
