/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type { ErrorType } from '../../../../../custom-instance';
import { customInstance } from '../../../../../custom-instance';
import type {
  AcceptedDeviceLoginRequest,
  CreatedDeviceLoginRequest,
  DeviceLoginCreateBody,
  DeviceLoginRequest,
  N400BadRequestResponse,
  N404NotFoundResponse,
  PollDeviceLoginRequestParams,
} from '../../../../../models/v2/iam';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Begin a device login flow
 */
export const requestDeviceLogin = (
  deviceLoginCreateBody: DeviceLoginCreateBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreatedDeviceLoginRequest>(
    {
      url: `/auth/device`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deviceLoginCreateBody,
      signal,
    },
    options,
  );
};

export const getRequestDeviceLoginMutationOptions = <
  TError = ErrorType<N400BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestDeviceLogin>>,
    TError,
    { data: DeviceLoginCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestDeviceLogin>>,
  TError,
  { data: DeviceLoginCreateBody },
  TContext
> => {
  const mutationKey = ['requestDeviceLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestDeviceLogin>>,
    { data: DeviceLoginCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return requestDeviceLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestDeviceLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestDeviceLogin>>
>;
export type RequestDeviceLoginMutationBody = DeviceLoginCreateBody;
export type RequestDeviceLoginMutationError = ErrorType<N400BadRequestResponse>;

/**
 * @summary Begin a device login flow
 */
export const useRequestDeviceLogin = <
  TError = ErrorType<N400BadRequestResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestDeviceLogin>>,
      TError,
      { data: DeviceLoginCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestDeviceLogin>>,
  TError,
  { data: DeviceLoginCreateBody },
  TContext
> => {
  const mutationOptions = getRequestDeviceLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Poll the device login request and attempt to redeem for a session token
 */
export const pollDeviceLoginRequest = (
  requestId: string,
  params: PollDeviceLoginRequestParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AcceptedDeviceLoginRequest | void>(
    { url: `/devicelogins/${requestId}/actions/poll`, method: 'POST', params, signal },
    options,
  );
};

export const getPollDeviceLoginRequestMutationOptions = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pollDeviceLoginRequest>>,
    TError,
    { requestId: string; params: PollDeviceLoginRequestParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pollDeviceLoginRequest>>,
  TError,
  { requestId: string; params: PollDeviceLoginRequestParams },
  TContext
> => {
  const mutationKey = ['pollDeviceLoginRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pollDeviceLoginRequest>>,
    { requestId: string; params: PollDeviceLoginRequestParams }
  > = (props) => {
    const { requestId, params } = props ?? {};

    return pollDeviceLoginRequest(requestId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PollDeviceLoginRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof pollDeviceLoginRequest>>
>;

export type PollDeviceLoginRequestMutationError = ErrorType<
  N400BadRequestResponse | N404NotFoundResponse
>;

/**
 * @summary Poll the device login request and attempt to redeem for a session token
 */
export const usePollDeviceLoginRequest = <
  TError = ErrorType<N400BadRequestResponse | N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pollDeviceLoginRequest>>,
      TError,
      { requestId: string; params: PollDeviceLoginRequestParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pollDeviceLoginRequest>>,
  TError,
  { requestId: string; params: PollDeviceLoginRequestParams },
  TContext
> => {
  const mutationOptions = getPollDeviceLoginRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary View the attributes of a device login request
 */
export const getDeviceLoginRequest = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DeviceLoginRequest>(
    { url: `/devicelogins/${code}`, method: 'GET', signal },
    options,
  );
};

export const getGetDeviceLoginRequestQueryKey = (code?: string) => {
  return [`/devicelogins/${code}`] as const;
};

export const getGetDeviceLoginRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeviceLoginRequest>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceLoginRequest>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDeviceLoginRequestQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeviceLoginRequest>>> = ({ signal }) =>
    getDeviceLoginRequest(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceLoginRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDeviceLoginRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDeviceLoginRequest>>
>;
export type GetDeviceLoginRequestQueryError = ErrorType<N404NotFoundResponse>;

export function useGetDeviceLoginRequest<
  TData = Awaited<ReturnType<typeof getDeviceLoginRequest>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  code: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceLoginRequest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceLoginRequest>>,
          TError,
          Awaited<ReturnType<typeof getDeviceLoginRequest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDeviceLoginRequest<
  TData = Awaited<ReturnType<typeof getDeviceLoginRequest>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceLoginRequest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceLoginRequest>>,
          TError,
          Awaited<ReturnType<typeof getDeviceLoginRequest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDeviceLoginRequest<
  TData = Awaited<ReturnType<typeof getDeviceLoginRequest>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceLoginRequest>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary View the attributes of a device login request
 */

/**
 *
 */
export function useGetDeviceLoginRequest<
  TData = Awaited<ReturnType<typeof getDeviceLoginRequest>>,
  TError = ErrorType<N404NotFoundResponse>,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceLoginRequest>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDeviceLoginRequestQueryOptions(code, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Accept the device login request and allocate it a session token.
 */
export const acceptDeviceLoginRequest = (
  requestId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/devicelogins/${requestId}/actions/accept`, method: 'POST', signal },
    options,
  );
};

export const getAcceptDeviceLoginRequestMutationOptions = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptDeviceLoginRequest>>,
    TError,
    { requestId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptDeviceLoginRequest>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['acceptDeviceLoginRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptDeviceLoginRequest>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return acceptDeviceLoginRequest(requestId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptDeviceLoginRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptDeviceLoginRequest>>
>;

export type AcceptDeviceLoginRequestMutationError = ErrorType<N404NotFoundResponse>;

/**
 * @summary Accept the device login request and allocate it a session token.
 */
export const useAcceptDeviceLoginRequest = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptDeviceLoginRequest>>,
      TError,
      { requestId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptDeviceLoginRequest>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationOptions = getAcceptDeviceLoginRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Reject the device login request
 */
export const rejectDeviceLoginRequest = (
  requestId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/devicelogins/${requestId}/actions/reject`, method: 'POST', signal },
    options,
  );
};

export const getRejectDeviceLoginRequestMutationOptions = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rejectDeviceLoginRequest>>,
    TError,
    { requestId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rejectDeviceLoginRequest>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['rejectDeviceLoginRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rejectDeviceLoginRequest>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return rejectDeviceLoginRequest(requestId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RejectDeviceLoginRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof rejectDeviceLoginRequest>>
>;

export type RejectDeviceLoginRequestMutationError = ErrorType<N404NotFoundResponse>;

/**
 * @summary Reject the device login request
 */
export const useRejectDeviceLoginRequest = <
  TError = ErrorType<N404NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rejectDeviceLoginRequest>>,
      TError,
      { requestId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rejectDeviceLoginRequest>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationOptions = getRejectDeviceLoginRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
