/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { http, HttpResponse } from 'msw';

import type {
  ModuleProvider,
  ModuleProviderPage,
  N400BadRequestResponse,
  N404NotFoundResponse,
  N409ConflictResponse,
} from '../../../../../models/v2/controlplane';

export const getListModuleProvidersResponseMock = (
  overrideResponse: Partial<ModuleProviderPage> = {},
): ModuleProviderPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  })),
  next_page_token: undefined,
  ...overrideResponse,
});

export const getListModuleProvidersResponseMock200 = (
  overrideResponse: Partial<ModuleProviderPage> = {},
): ModuleProviderPage => ({
  items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  })),
  next_page_token: undefined,
  ...overrideResponse,
});

export const getListModuleProvidersResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateModuleProviderResponseMock = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getCreateModuleProviderResponseMock201 = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getCreateModuleProviderResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getCreateModuleProviderResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getGetModuleProviderResponseMock = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getGetModuleProviderResponseMock200 = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getGetModuleProviderResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getUpdateModuleProviderResponseMock = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getUpdateModuleProviderResponseMock200 = (): ModuleProvider => ({
  ...{
    org_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    provider_type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    source: faker.string.alpha({ length: { min: 10, max: 20 } }),
    created_at: `${faker.date.past().toISOString().split('.')[0]}Z`,
  },
  ...{
    version_constraint: faker.string.alpha({ length: { min: 10, max: 20 } }),
    configuration: {},
  },
});

export const getUpdateModuleProviderResponseMock400 = (
  overrideResponse: Partial<N400BadRequestResponse> = {},
): N400BadRequestResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getUpdateModuleProviderResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getUpdateModuleProviderResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getDeleteModuleProviderResponseMock404 = (
  overrideResponse: Partial<N404NotFoundResponse> = {},
): N404NotFoundResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getDeleteModuleProviderResponseMock409 = (
  overrideResponse: Partial<N409ConflictResponse> = {},
): N409ConflictResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  details: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
});

export const getListModuleProvidersMockHandler = (
  overrideResponse?:
    | ModuleProviderPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ModuleProviderPage> | ModuleProviderPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListModuleProvidersResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getListModuleProvidersMockHandler200 = (
  overrideResponse?:
    | ModuleProviderPage
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ModuleProviderPage> | ModuleProviderPage),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListModuleProvidersResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getListModuleProvidersMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListModuleProvidersResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateModuleProviderMockHandler = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateModuleProviderResponseMock(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateModuleProviderMockHandler201 = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateModuleProviderResponseMock201(),
        ),
        { status: 201, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateModuleProviderMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateModuleProviderResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCreateModuleProviderMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    'http://example.com/orgs/:orgId/module-providers',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateModuleProviderResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetModuleProviderMockHandler = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetModuleProviderResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetModuleProviderMockHandler200 = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetModuleProviderResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetModuleProviderMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetModuleProviderResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateModuleProviderMockHandler = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateModuleProviderResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateModuleProviderMockHandler200 = (
  overrideResponse?:
    | ModuleProvider
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ModuleProvider> | ModuleProvider),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateModuleProviderResponseMock200(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateModuleProviderMockHandler400 = (
  overrideResponse?:
    | N400BadRequestResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<N400BadRequestResponse> | N400BadRequestResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateModuleProviderResponseMock400(),
        ),
        { status: 400, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateModuleProviderMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateModuleProviderResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUpdateModuleProviderMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateModuleProviderResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteModuleProviderMockHandler = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteModuleProviderMockHandler204 = (
  overrideResponse?:
    | void
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteModuleProviderMockHandler404 = (
  overrideResponse?:
    | N404NotFoundResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<N404NotFoundResponse> | N404NotFoundResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteModuleProviderResponseMock404(),
        ),
        { status: 404, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeleteModuleProviderMockHandler409 = (
  overrideResponse?:
    | N409ConflictResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<N409ConflictResponse> | N409ConflictResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    'http://example.com/orgs/:orgId/module-providers/:providerType/:providerId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteModuleProviderResponseMock409(),
        ),
        { status: 409, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getProvidersMock = () => [
  getListModuleProvidersMockHandler(),
  getCreateModuleProviderMockHandler(),
  getGetModuleProviderMockHandler(),
  getUpdateModuleProviderMockHandler(),
  getDeleteModuleProviderMockHandler(),
];
